import { TournamentData } from "../types";
import { worldCup1930 } from "./world-cup-data/worldCup1930";
import { worldCup1934 } from "./world-cup-data/worldCup1934";
import { worldCup1938 } from "./world-cup-data/worldCup1938";
import { worldCup1950 } from "./world-cup-data/worldCup1950";
import { worldCup1954 } from "./world-cup-data/worldCup1954";
import { worldCup1958 } from "./world-cup-data/worldCup1958";
import { worldCup1962 } from "./world-cup-data/worldCup1962";
import { worldCup1966 } from "./world-cup-data/worldCup1966";
import { worldCup1970 } from "./world-cup-data/worldCup1970";
import { worldCup1974 } from "./world-cup-data/worldCup1974";
import { worldCup1978 } from "./world-cup-data/worldCup1978";
import { worldCup1982 } from "./world-cup-data/worldCup1982";
import { worldCup1986 } from "./world-cup-data/worldCup1986";

export const worldCupStore: TournamentData = {
  1930: worldCup1930,
  1934: worldCup1934,
  1938: worldCup1938,
  1950: worldCup1950,
  1954: worldCup1954,
  1958: worldCup1958,
  1962: worldCup1962,
  1966: worldCup1966,
  1970: worldCup1970,
  1974: worldCup1974,
  1978: worldCup1978,
  1982: worldCup1982,
  1986: worldCup1986,

//   1990: {
//     id: 'world-cup.14.1990',
//     title: '1990 FIFA World Cup',
//     date: '	8June - 8 July',
//     icon: logoWorldCup1990,
//     background: [backgroundFWC1990_1, backgroundFWC1990_2],
//     hostCountry: ['Italy'],
//     finalStage: [
//       new Match(
//         '09.06.1990',
//         stage.group.a,
//         ['Italy', 'Austria'],
//         [[1, 0], [], []],
//         ['S.Schillaci'],
//         ['78'],
//         [],
//         [],
//         stadiumsData.Italy.olimpico,
//         '73 303'
//       ),
//       new Match(
//         '10.06.1990',
//         stage.group.a,
//         ['Czechoslovakia', 'United States'],
//         [[5, 1], [], []],
//         ['T.Skuhravy', 'M.Bílek', 'I.Hašek', 'M.Luhovy'],
//         ['25, 78', '39', '50', '90'],
//         ['P.Caligiuri'],
//         ['61'],
//         stadiumsData.Italy.comunale,
//         '33 266'
//       ),
//       new Match(
//         '14.06.1990',
//         stage.group.a,
//         ['Italy', 'United States'],
//         [[1, 0], [], []],
//         ['G.Giannini'],
//         ['11'],
//         [],
//         [],
//         stadiumsData.Italy.olimpico,
//         '73 423'
//       ),
//       new Match(
//         '15.06.1990',
//         stage.group.a,
//         ['Czechoslovakia', 'Austria'],
//         [[1, 0], [], []],
//         ['M.Bílek'],
//         ['30'],
//         [],
//         [],
//         stadiumsData.Italy.comunale,
//         '38 962'
//       ),
//       new Match(
//         '19.06.1990',
//         stage.group.a,
//         ['Italy', 'Czechoslovakia'],
//         [[2, 0], [], []],
//         ['S.Schillaci', 'R.Baggio'],
//         ['10', '78'],
//         [],
//         [],
//         stadiumsData.Italy.olimpico,
//         '73 303'
//       ),
//       new Match(
//         '19.06.1990',
//         stage.group.a,
//         ['Austria', 'United States'],
//         [[2, 1], [], []],
//         ['A.Ogris', 'G.Rodax'],
//         ['52', '65'],
//         ['B.Murray'],
//         ['85'],
//         stadiumsData.Italy.comunale,
//         '34 857'
//       ),
//       new Match(
//         '08.06.1990',
//         stage.group.b,
//         ['Cameroon', 'Argentina'],
//         [[1, 0], [], []],
//         ['F.Omam-Biyik'],
//         ['65'],
//         [],
//         [],
//         stadiumsData.Italy.sanSiro,
//         '73 780'
//       ),
//       new Match(
//         '09.06.1990',
//         stage.group.b,
//         ['Romania', 'Soviet Union'],
//         [[2, 0], [], []],
//         ['M.Lăcătuș'],
//         ['41, 54(p)'],
//         [],
//         [],
//         stadiumsData.Italy.nicola,
//         '42 960'
//       ),
//       new Match(
//         '13.06.1990',
//         stage.group.b,
//         ['Argentina', 'Soviet Union'],
//         [[2, 0], [], []],
//         ['P.Troglio', 'J.Burruchaga'],
//         ['27', '79'],
//         [],
//         [],
//         stadiumsData.Italy.paolo,
//         '55 759'
//       ),
//       new Match(
//         '14.06.1990',
//         stage.group.b,
//         ['Cameroon', 'Romania'],
//         [[2, 1], [], []],
//         ['R.Milla'],
//         ['76, 86'],
//         ['G.Balint'],
//         ['88'],
//         stadiumsData.Italy.nicola,
//         '38 687'
//       ),
//       new Match(
//         '18.06.1990',
//         stage.group.b,
//         ['Argentina', 'Romania'],
//         [[1, 1], [], []],
//         ['P.Monzón'],
//         ['62'],
//         ['G.Balint'],
//         ['68'],
//         stadiumsData.Italy.paolo,
//         '52 733'
//       ),
//       new Match(
//         '18.06.1990',
//         stage.group.b,
//         ['Soviet Union', 'Cameroon'],
//         [[4, 0], [], []],
//         ['O.Protasov', 'A.Zygmantovich', 'O.Zavarov', 'I.Dobrovolskiy'],
//         ['20', '29', '52', '63'],
//         [],
//         [],
//         stadiumsData.Italy.nicola,
//         '37 307'
//       ),
//       new Match(
//         '10.06.1990',
//         stage.group.c,
//         ['Brazil', 'Sweden'],
//         [[2, 1], [], []],
//         ['Careca'],
//         ['40, 63'],
//         ['T.Brolin'],
//         ['79'],
//         stadiumsData.Italy.alpi,
//         '62 628'
//       ),
//       new Match(
//         '11.06.1990',
//         stage.group.c,
//         ['Costa Rica', 'Scotland'],
//         [[1, 0], [], []],
//         ['J.Cayasso'],
//         ['49'],
//         [],
//         [],
//         stadiumsData.Italy.ferraris,
//         '30 867'
//       ),
//       new Match(
//         '16.06.1990',
//         stage.group.c,
//         ['Brazil', 'Costa Rica'],
//         [[1, 0], [], []],
//         ['Müller'],
//         ['33'],
//         [],
//         [],
//         stadiumsData.Italy.alpi,
//         '58 007'
//       ),
//       new Match(
//         '16.06.1990',
//         stage.group.c,
//         ['Scotland', 'Sweden'],
//         [[2, 1], [], []],
//         ['S.McCall', 'M.Johnston'],
//         ['11', '80(p)'],
//         ['G.Strömberg'],
//         ['86'],
//         stadiumsData.Italy.ferraris,
//         '31 823'
//       ),
//       new Match(
//         '20.06.1990',
//         stage.group.c,
//         ['Brazil', 'Scotland'],
//         [[1, 0], [], []],
//         ['Müller'],
//         ['82'],
//         [],
//         [],
//         stadiumsData.Italy.alpi,
//         '62 502'
//       ),
//       new Match(
//         '20.06.1990',
//         stage.group.c,
//         ['Costa Rica', 'Sweden'],
//         [[2, 1], [], []],
//         ['R.Flores', 'H.Medford'],
//         ['75', '87'],
//         ['J.Ekstrom'],
//         ['32'],
//         stadiumsData.Italy.ferraris,
//         '20 223'
//       ),
//       new Match(
//         '09.06.1990',
//         stage.group.d,
//         ['Colombia', 'U. A. Emirates'],
//         [[2, 0], [], []],
//         ['B.Redín', 'C.Valderrama'],
//         ['50', '85'],
//         [],
//         [],
//         stadiumsData.Italy.dallAra,
//         '30 791'
//       ),
//       new Match(
//         '10.06.1990',
//         stage.group.d,
//         ['Germany', 'Yugoslavia'],
//         [[4, 1], [], []],
//         ['L.Matthäus', 'J.Klinsmann', 'R.Völler'],
//         ['28, 64', '39', '70'],
//         ['D.Jozić'],
//         ['55'],
//         stadiumsData.Italy.sanSiro,
//         '74 765'
//       ),
//       new Match(
//         '14.06.1990',
//         stage.group.d,
//         ['Yugoslavia', 'Colombia'],
//         [[1, 0], [], []],
//         ['D.Jozić'],
//         ['73'],
//         [],
//         [],
//         stadiumsData.Italy.dallAra,
//         '32 257'
//       ),
//       new Match(
//         '15.06.1990',
//         stage.group.d,
//         ['Germany', 'U. A. Emirates'],
//         [[5, 1], [], []],
//         ['R.Völler', 'J.Klinsmann', 'L.Matthäus', 'U.Bein'],
//         ['35, 75', '36', '47', '59'],
//         ['K.Ismaïl'],
//         ['46'],
//         stadiumsData.Italy.sanSiro,
//         '71 167'
//       ),
//       new Match(
//         '19.06.1990',
//         stage.group.d,
//         ['Germany', 'Colombia'],
//         [[1, 1], [], []],
//         ['P.Littbarski'],
//         ['88'],
//         ['F.Rincón'],
//         ['90+3'],
//         stadiumsData.Italy.sanSiro,
//         '72 510'
//       ),
//       new Match(
//         '19.06.1990',
//         stage.group.d,
//         ['Yugoslavia', 'U. A. Emirates'],
//         [[4, 1], [], []],
//         ['S.Sušić', 'D.Pancev', 'R.Prosinečki'],
//         ['5', '9, 46', '90'],
//         ["A.T.Juma'a"],
//         ['22'],
//         stadiumsData.Italy.dallAra,
//         '27 833'
//       ),
//       new Match(
//         '12.06.1990',
//         stage.group.e,
//         ['Belgium', 'Korea Republic'],
//         [[2, 0], [], []],
//         ['M.Degryse', 'M.De Wolf'],
//         ['53', '64'],
//         [],
//         [],
//         stadiumsData.Italy.bentegodi,
//         '32 486'
//       ),
//       new Match(
//         '13.06.1990',
//         stage.group.e,
//         ['Uruguay', 'Spain'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Italy.friuli,
//         '35 713'
//       ),
//       new Match(
//         '17.06.1990',
//         stage.group.e,
//         ['Belgium', 'Uruguay'],
//         [[3, 1], [], []],
//         ['L.Clijsters', 'E.Scifo', 'J.Ceulemans'],
//         ['15', '22', '47'],
//         ['P.J.Bengoechea'],
//         ['73'],
//         stadiumsData.Italy.bentegodi,
//         '33 759'
//       ),
//       new Match(
//         '17.06.1990',
//         stage.group.e,
//         ['Spain', 'Korea Republic'],
//         [[3, 1], [], []],
//         ['Michel'],
//         ['23, 61, 81'],
//         ['Hwang-Bo Kwan'],
//         ['43'],
//         stadiumsData.Italy.friuli,
//         '32 733'
//       ),
//       new Match(
//         '21.06.1990',
//         stage.group.e,
//         ['Spain', 'Belgium'],
//         [[2, 1], [], []],
//         ['Michel', 'Górriz'],
//         ['27(p)', '38'],
//         ['P.Vervoort'],
//         ['29'],
//         stadiumsData.Italy.bentegodi,
//         '35 950'
//       ),
//       new Match(
//         '21.06.1990',
//         stage.group.e,
//         ['Uruguay', 'Korea Republic'],
//         [[1, 0], [], []],
//         ['D.Fonseca'],
//         ['90'],
//         [],
//         [],
//         stadiumsData.Italy.friuli,
//         '29 039'
//       ),
//       new Match(
//         '11.06.1990',
//         stage.group.f,
//         ['England', 'Ireland'],
//         [[1, 1], [], []],
//         ['G.Lineker'],
//         ['9'],
//         ['K.Sheedy'],
//         ['73'],
//         stadiumsData.Italy.santElia,
//         '35 238'
//       ),
//       new Match(
//         '12.06.1990',
//         stage.group.f,
//         ['Netherlands', 'Egypt'],
//         [[1, 1], [], []],
//         ['W.Kieft'],
//         ['58'],
//         ['M.Abdelghany'],
//         ['83(p)'],
//         stadiumsData.Italy.favorita,
//         '33 421'
//       ),
//       new Match(
//         '16.06.1990',
//         stage.group.f,
//         ['England', 'Netherlands'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Italy.santElia,
//         '35 267'
//       ),
//       new Match(
//         '17.06.1990',
//         stage.group.f,
//         ['Ireland', 'Egypt'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Italy.favorita,
//         '33 288'
//       ),
//       new Match(
//         '21.06.1990',
//         stage.group.f,
//         ['England', 'Egypt'],
//         [[1, 0], [], []],
//         ['M.Wright'],
//         ['58'],
//         [],
//         [],
//         stadiumsData.Italy.santElia,
//         '34 959'
//       ),
//       new Match(
//         '21.06.1990',
//         stage.group.f,
//         ['Ireland', 'Netherlands'],
//         [[1, 1], [], []],
//         ['N.Quinn'],
//         ['71'],
//         ['R.Gullit'],
//         ['11'],
//         stadiumsData.Italy.favorita,
//         '33 288'
//       ),
//       new Match(
//         '23.06.1990',
//         stage[1_8],
//         ['Cameroon', 'Colombia'],
//         [[0, 0], [2, 1], []],
//         ['R.Milla'],
//         ['106, 108'],
//         ['B.Redín'],
//         ['115'],
//         stadiumsData.Italy.paolo,
//         '50 026'
//       ),
//       new Match(
//         '23.06.1990',
//         stage[1_8],
//         ['Czechoslovakia', 'Costa Rica'],
//         [[4, 1], [], []],
//         ['T.Skuhravy', 'L.Kubik'],
//         ['12, 63, 82', '76'],
//         ['R.González'],
//         ['55'],
//         stadiumsData.Italy.nicola,
//         '47 673'
//       ),
//       new Match(
//         '24.06.1990',
//         stage[1_8],
//         ['Argentina', 'Brazil'],
//         [[1, 0], [], []],
//         ['C.Caniggia'],
//         ['81'],
//         [],
//         [],
//         stadiumsData.Italy.alpi,
//         '61 381'
//       ),
//       new Match(
//         '24.06.1990',
//         stage[1_8],
//         ['Germany', 'Netherlands'],
//         [[2, 1], [], []],
//         ['J.Klinsmann', 'A.Brehme'],
//         ['51', '85'],
//         ['R.Koeman'],
//         ['89(p)'],
//         stadiumsData.Italy.sanSiro,
//         '74 559'
//       ),
//       new Match(
//         '25.06.1990',
//         stage[1_8],
//         ['Ireland', 'Romania'],
//         [
//           [0, 0],
//           [0, 0],
//           [5, 4],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Italy.ferraris,
//         '31 818'
//       ),
//       new Match(
//         '25.06.1990',
//         stage[1_8],
//         ['Italy', 'Uruguay'],
//         [[2, 0], [], []],
//         ['S.Schillaci', 'A.Serena'],
//         ['65', '85'],
//         [],
//         [],
//         stadiumsData.Italy.olimpico,
//         '73 303'
//       ),
//       new Match(
//         '26.06.1990',
//         stage[1_8],
//         ['Yugoslavia', 'Spain'],
//         [[1, 1], [1, 0], []],
//         ['D.Stojković'],
//         ['78', '92'],
//         ['J.Salinas'],
//         ['83'],
//         stadiumsData.Italy.bentegodi,
//         '35 500'
//       ),
//       new Match(
//         '26.06.1990',
//         stage[1_8],
//         ['England', 'Belgium'],
//         [[0, 0], [1, 0], []],
//         ['D.Platt'],
//         ['119'],
//         [],
//         [],
//         stadiumsData.Italy.dallAra,
//         '34 520'
//       ),
//       new Match(
//         '30.06.1990',
//         stage[1_4],
//         ['Argentina', 'Yugoslavia'],
//         [
//           [0, 0],
//           [0, 0],
//           [3, 2],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Italy.comunale,
//         '38 971'
//       ),
//       new Match(
//         '30.06.1990',
//         stage[1_4],
//         ['Italy', 'Ireland'],
//         [[1, 0], [], []],
//         ['S.Schillaci'],
//         ['38'],
//         [],
//         [],
//         stadiumsData.Italy.olimpico,
//         '73 303'
//       ),
//       new Match(
//         '01.07.1990',
//         stage[1_4],
//         ['Germany', 'Czechoslovakia'],
//         [[1, 0], [], []],
//         ['L.Matthäus'],
//         ['25(p)'],
//         [],
//         [],
//         stadiumsData.Italy.sanSiro,
//         '73 347'
//       ),
//       new Match(
//         '01.07.1990',
//         stage[1_4],
//         ['England', 'Cameroon'],
//         [[2, 2], [1, 0], []],
//         ['D.Platt', 'G.Lineker'],
//         ['25', '83(p), 105(p)'],
//         ['E.Kundé', 'E.Ekéké'],
//         ['61(p)', '65'],
//         stadiumsData.Italy.paolo,
//         '55 205'
//       ),
//       new Match(
//         '03.07.1990',
//         stage[1_2],
//         ['Argentina', 'Italy'],
//         [
//           [1, 1],
//           [0, 0],
//           [4, 3],
//         ],
//         ['C.Caniggia'],
//         ['67'],
//         ['S.Schillaci'],
//         ['17'],
//         stadiumsData.Italy.paolo,
//         '59 978'
//       ),
//       new Match(
//         '04.07.1990',
//         stage[1_2],
//         ['Germany', 'England'],
//         [
//           [1, 1],
//           [0, 0],
//           [4, 3],
//         ],
//         ['A.Brehme'],
//         ['60'],
//         ['G.Lineker'],
//         ['80'],
//         stadiumsData.Italy.alpi,
//         '62 628'
//       ),
//       new Match(
//         '07.07.1990',
//         stage.place3,
//         ['Italy', 'England'],
//         [[2, 1], [], []],
//         ['R.Baggio', 'S.Schillaci'],
//         ['71', '86(p)'],
//         ['D.Platt'],
//         ['81'],
//         stadiumsData.Italy.nicola,
//         '51 426'
//       ),
//       new Match(
//         '08.07.1990',
//         stage.final,
//         ['Germany', 'Argentina'],
//         [[1, 0], [], []],
//         ['A.Brehme'],
//         ['85(p)'],
//         [],
//         [],
//         stadiumsData.Italy.olimpico,
//         '73 603'
//       ),
//     ],
//     qualification: [],
//   },
//   1994: {
//     id: 'world-cup.15.1994',
//     title: '1994 FIFA World Cup',
//     date: 'June 17 - July 17',
//     icon: logoWorldCup1994,
//     background: [backgroundFWC1994_1, backgroundFWC1994_2],
//     hostCountry: ['United States'],
//     finalStage: [
//       new Match(
//         '18.06.1994',
//         stage.group.a,
//         ['United States', 'Switzerland'],
//         [[1, 1], [], []],
//         ['E.Wynalda'],
//         ['45'],
//         ['G.Bregy'],
//         ['39'],
//         stadiumsData.USA.pontiac,
//         '73 425'
//       ),
//       new Match(
//         '18.06.1994',
//         stage.group.a,
//         ['Romania', 'Colombia'],
//         [[3, 1], [], []],
//         ['F.Răducioiu', 'G.Hagi'],
//         ['16, 89', '34'],
//         ['A.Valencia'],
//         ['43'],
//         stadiumsData.USA.rose,
//         '91 856'
//       ),
//       new Match(
//         '22.06.1994',
//         stage.group.a,
//         ['Switzerland', 'Romania'],
//         [[4, 1], [], []],
//         ['A.Sutter', 'S.Chapuisat', 'A.Knup'],
//         ['16', '52', '66, 72'],
//         ['G.Hagi'],
//         ['35'],
//         stadiumsData.USA.pontiac,
//         '61 428'
//       ),
//       new Match(
//         '22.06.1994',
//         stage.group.a,
//         ['United States', 'Colombia'],
//         [[2, 1], [], []],
//         ['A.Escobar', 'E.Stewart'],
//         ['35(o.g.)', '52'],
//         ['A.Valencia'],
//         ['90'],
//         stadiumsData.USA.rose,
//         '93 869'
//       ),
//       new Match(
//         '26.06.1994',
//         stage.group.a,
//         ['Colombia', 'Switzerland'],
//         [[2, 0], [], []],
//         ['H.Gaviria', 'H.Lozano'],
//         ['44', '90+1'],
//         [],
//         [],
//         stadiumsData.USA.stanford,
//         '83 401'
//       ),
//       new Match(
//         '26.06.1994',
//         stage.group.a,
//         ['Romania', 'United States'],
//         [[1, 0], [], []],
//         ['D.Petrescu'],
//         ['18'],
//         [],
//         [],
//         stadiumsData.USA.rose,
//         '93 869'
//       ),
//       new Match(
//         '19.06.1994',
//         stage.group.b,
//         ['Cameroon', 'Sweden'],
//         [[2, 2], [], []],
//         ['J.-D.Embe', 'F.Omam-Biyik'],
//         ['31', '47'],
//         ['R.Ljung', 'M.Dahlin'],
//         ['8', '75'],
//         stadiumsData.USA.rose,
//         '93 194'
//       ),
//       new Match(
//         '20.06.1994',
//         stage.group.b,
//         ['Brazil', 'Russia'],
//         [[2, 0], [], []],
//         ['Romário', 'Raí'],
//         ['26', '52(p)'],
//         [],
//         [],
//         stadiumsData.USA.stanford,
//         '81 061'
//       ),
//       new Match(
//         '24.06.1994',
//         stage.group.b,
//         ['Brazil', 'Cameroon'],
//         [[3, 0], [], []],
//         ['Romário', 'Márcio Santos', 'Bebeto'],
//         ['39', '66', '73'],
//         [],
//         [],
//         stadiumsData.USA.stanford,
//         '83 401'
//       ),
//       new Match(
//         '24.06.1994',
//         stage.group.b,
//         ['Sweden', 'Russia'],
//         [[3, 1], [], []],
//         ['T.Brolin', 'M.Dahlin'],
//         ['37(p)', '59, 81'],
//         ['O.Salenko'],
//         ['4(p)'],
//         stadiumsData.USA.pontiac,
//         '71 528'
//       ),
//       new Match(
//         '28.06.1994',
//         stage.group.b,
//         ['Russia', 'Cameroon'],
//         [[6, 1], [], []],
//         ['O.Salenko', 'D.Radchenko'],
//         ['15, 41, 44(p), 72, 75', '81'],
//         ['R.Milla'],
//         ['46'],
//         stadiumsData.USA.stanford,
//         '74 914'
//       ),
//       new Match(
//         '28.06.1994',
//         stage.group.b,
//         ['Brazil', 'Sweden'],
//         [[1, 1], [], []],
//         ['Romário'],
//         ['47'],
//         ['K.Andersson'],
//         ['23'],
//         stadiumsData.USA.pontiac,
//         '77 217'
//       ),
//       new Match(
//         '17.06.1994',
//         stage.group.c,
//         ['Germany', 'Bolivia'],
//         [[1, 0], [], []],
//         ['J.Klinsmann'],
//         ['61'],
//         [],
//         [],
//         stadiumsData.USA.soldier,
//         '63 117'
//       ),
//       new Match(
//         '17.06.1994',
//         stage.group.c,
//         ['Spain', 'Korea Republic'],
//         [[2, 2], [], []],
//         ['J.alinas', 'A.Goikoetxea'],
//         ['51', '56'],
//         ['Hong Myung-bo', 'Seo Jung-won'],
//         ['85', '90'],
//         stadiumsData.USA.cotton,
//         '56 247'
//       ),
//       new Match(
//         '21.06.1994',
//         stage.group.c,
//         ['Germany', 'Spain'],
//         [[1, 1], [], []],
//         ['J.Klinsmann'],
//         ['48'],
//         ['A.Goikoetxea'],
//         ['14'],
//         stadiumsData.USA.soldier,
//         '63 113'
//       ),
//       new Match(
//         '23.06.1994',
//         stage.group.c,
//         ['Korea Republic', 'Bolivia'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.USA.foxboro,
//         '54 453'
//       ),
//       new Match(
//         '27.06.1994',
//         stage.group.c,
//         ['Spain', 'Bolivia'],
//         [[3, 1], [], []],
//         ['P.Guardiola', 'J.L.Caminero'],
//         ['19(p)', '66, 70'],
//         ['E.Sanchez'],
//         ['67'],
//         stadiumsData.USA.soldier,
//         '63 089'
//       ),
//       new Match(
//         '27.06.1994',
//         stage.group.c,
//         ['Germany', 'Korea Republic'],
//         [[3, 2], [], []],
//         ['J.Klinsmann', 'K.-H.Riedle'],
//         ['12, 37', '20'],
//         ['Hwang Sun-hong', 'Hong Myung-bo'],
//         ['52', '63'],
//         stadiumsData.USA.cotton,
//         '63 998'
//       ),
//       new Match(
//         '21.06.1994',
//         stage.group.d,
//         ['Argentina', 'Greece'],
//         [[4, 0], [], []],
//         ['G.Batistuta', 'D.Maradona'],
//         ['2, 44, 90(p)', '60'],
//         [],
//         [],
//         stadiumsData.USA.foxboro,
//         '54 456'
//       ),
//       new Match(
//         '21.06.1994',
//         stage.group.d,
//         ['Nigeria', 'Bulgaria'],
//         [[3, 0], [], []],
//         ['R.Yekini', 'D.Amokachi', 'E.Amunike'],
//         ['21', '43', '55'],
//         [],
//         [],
//         stadiumsData.USA.cotton,
//         '44 132'
//       ),
//       new Match(
//         '25.06.1994',
//         stage.group.d,
//         ['Argentina', 'Nigeria'],
//         [[2, 1], [], []],
//         ['C.Caniggia'],
//         ['21, 28'],
//         ['S.Siasia'],
//         ['8'],
//         stadiumsData.USA.foxboro,
//         '54 453'
//       ),
//       new Match(
//         '26.06.1994',
//         stage.group.d,
//         ['Bulgaria', 'Greece'],
//         [[4, 0], [], []],
//         ['H.Stoichkov', 'Y.Letchkov', 'D.Borimirov'],
//         ['5(p), 55', '66', '90'],
//         [],
//         [],
//         stadiumsData.USA.soldier,
//         '63 160'
//       ),
//       new Match(
//         '30.06.1994',
//         stage.group.d,
//         ['Bulgaria', 'Argentina'],
//         [[2, 0], [], []],
//         ['H.Stoichkov', 'N.Sirakov'],
//         ['61', '90+3'],
//         [],
//         [],
//         stadiumsData.USA.cotton,
//         '63 998'
//       ),
//       new Match(
//         '30.06.1994',
//         stage.group.d,
//         ['Nigeria', 'Greece'],
//         [[2, 0], [], []],
//         ['F.George', 'D.Amokachi'],
//         ['45+2', '90+5'],
//         [],
//         [],
//         stadiumsData.USA.foxboro,
//         '53 001'
//       ),
//       new Match(
//         '18.06.1994',
//         stage.group.e,
//         ['Ireland', 'Italy'],
//         [[1, 0], [], []],
//         ['R.Houghton'],
//         ['12'],
//         [],
//         [],
//         stadiumsData.USA.giants,
//         '75 338'
//       ),
//       new Match(
//         '19.06.1994',
//         stage.group.e,
//         ['Norway', 'Mexico'],
//         [[1, 0], [], []],
//         ['K.Rekdal'],
//         ['85'],
//         [],
//         [],
//         stadiumsData.USA.kennedy,
//         '52 395'
//       ),
//       new Match(
//         '23.06.1994',
//         stage.group.e,
//         ['Italy', 'Norway'],
//         [[1, 0], [], []],
//         ['D.Baggio'],
//         ['69'],
//         [],
//         [],
//         stadiumsData.USA.giants,
//         '74 624'
//       ),
//       new Match(
//         '24.06.1994',
//         stage.group.e,
//         ['Mexico', 'Ireland'],
//         [[2, 1], [], []],
//         ['Luis Garcia'],
//         ['42, 65'],
//         ['J.Aldridge'],
//         ['84'],
//         stadiumsData.USA.citrus,
//         '60 790'
//       ),
//       new Match(
//         '28.06.1994',
//         stage.group.e,
//         ['Italy', 'Mexico'],
//         [[1, 1], [], []],
//         ['D.Massaro'],
//         ['48'],
//         ['M.Bernal'],
//         ['57'],
//         stadiumsData.USA.kennedy,
//         '52 535'
//       ),
//       new Match(
//         '28.06.1994',
//         stage.group.e,
//         ['Ireland', 'Norway'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.USA.giants,
//         '72 404'
//       ),
//       new Match(
//         '19.06.1994',
//         stage.group.f,
//         ['Belgium', 'Morocco'],
//         [[1, 0], [], []],
//         ['M.Degryse'],
//         ['11'],
//         [],
//         [],
//         stadiumsData.USA.citrus,
//         '61 219'
//       ),
//       new Match(
//         '20.06.1994',
//         stage.group.f,
//         ['Netherlands', 'Saudi Arabia'],
//         [[2, 1], [], []],
//         ['W.Jonk', 'G.Taument'],
//         ['50', '86'],
//         ['F.Amin'],
//         ['18'],
//         stadiumsData.USA.kennedy,
//         '50 535'
//       ),
//       new Match(
//         '25.06.1994',
//         stage.group.f,
//         ['Belgium', 'Netherlands'],
//         [[1, 0], [], []],
//         ['P.Albert'],
//         ['65'],
//         [],
//         [],
//         stadiumsData.USA.citrus,
//         '62 387'
//       ),
//       new Match(
//         '25.06.1994',
//         stage.group.f,
//         ['Saudi Arabia', 'Morocco'],
//         [[2, 1], [], []],
//         ['Sami Al Jaber', 'F.Amin'],
//         ['7(p)', '45'],
//         ['M.Chaouch'],
//         ['26'],
//         stadiumsData.USA.giants,
//         '76 322'
//       ),
//       new Match(
//         '29.06.1990',
//         stage.group.f,
//         ['Saudi Arabia', 'Belgium'],
//         [[1, 0], [], []],
//         ['Said Al Owayran'],
//         ['5'],
//         [],
//         [],
//         stadiumsData.USA.kennedy,
//         '52 959'
//       ),
//       new Match(
//         '29.06.1994',
//         stage.group.f,
//         ['Netherlands', 'Morocco'],
//         [[2, 1], [], []],
//         ['D.Bergkamp', 'B.Roy'],
//         ['43', '77'],
//         ['H.Nader'],
//         ['47'],
//         stadiumsData.USA.citrus,
//         '60 578'
//       ),
//       new Match(
//         '02.07.1994',
//         stage[1_8],
//         ['Germany', 'Belgium'],
//         [[3, 2], [], []],
//         ['R.Völler', 'J.Klinsmann'],
//         ['6, 38', '11'],
//         ['G.Grün', 'P.Albert'],
//         ['8', '90'],
//         stadiumsData.USA.soldier,
//         '60 246'
//       ),
//       new Match(
//         '02.07.1994',
//         stage[1_8],
//         ['Spain', 'Switzerland'],
//         [[3, 0], [], []],
//         ['F.Hierro', 'Luis Enrique', 'Beguiristáin'],
//         ['15', '74', '86(p)'],
//         [],
//         [],
//         stadiumsData.USA.kennedy,
//         '53 121'
//       ),
//       new Match(
//         '03.07.1994',
//         stage[1_8],
//         ['Sweden', 'Saudi Arabia'],
//         [[3, 1], [], []],
//         ['M.Dahlin', 'K.Andersson'],
//         ['6', '51, 88'],
//         ['Fahad Al Ghesheyan'],
//         ['85'],
//         stadiumsData.USA.cotton,
//         '60 277'
//       ),
//       new Match(
//         '03.07.1994',
//         stage[1_8],
//         ['Romania', 'Argentina'],
//         [[3, 2], [], []],
//         ['I.Dumitrescu', 'G.Hagi'],
//         ['11, 18', '58'],
//         ['G.Batistuta', 'A.Balbo'],
//         ['16(p)', '75'],
//         stadiumsData.USA.rose,
//         '90 469'
//       ),
//       new Match(
//         '04.07.1994',
//         stage[1_8],
//         ['Netherlands', 'Ireland'],
//         [[2, 0], [], []],
//         ['D.Bergkamp', 'W.Jonk'],
//         ['11', '41'],
//         [],
//         [],
//         stadiumsData.USA.citrus,
//         '61 355'
//       ),
//       new Match(
//         '04.07.1994',
//         stage[1_8],
//         ['Brazil', 'United States'],
//         [[1, 0], [], []],
//         ['Bebeto'],
//         ['72'],
//         [],
//         [],
//         stadiumsData.USA.stanford,
//         '84 147'
//       ),
//       new Match(
//         '05.07.1994',
//         stage[1_8],
//         ['Italy', 'Nigeria'],
//         [[1, 1], [1, 0], []],
//         ['R.Baggio'],
//         ['88', '102'],
//         ['E.Amunike'],
//         ['25'],
//         stadiumsData.USA.foxboro,
//         '54 367'
//       ),
//       new Match(
//         '05.07.1994',
//         stage[1_8],
//         ['Bulgaria', 'Mexico'],
//         [
//           [1, 1],
//           [0, 0],
//           [3, 1],
//         ],
//         ['H.Stoichkov'],
//         ['6'],
//         ['García Aspe'],
//         ['18(p)'],
//         stadiumsData.USA.giants,
//         '71 030'
//       ),
//       new Match(
//         '09.07.1994',
//         stage[1_4],
//         ['Italy', 'Spain'],
//         [[2, 1], [], []],
//         ['D.Baggio', 'R.Baggio'],
//         ['25', '88'],
//         ['J.L.Caminero'],
//         ['58'],
//         stadiumsData.USA.foxboro,
//         '53 400'
//       ),
//       new Match(
//         '09.07.1994',
//         stage[1_4],
//         ['Brazil', 'Netherlands'],
//         [[3, 2], [], []],
//         ['Romário', 'Bebeto', 'Branco'],
//         ['53', '63', '81'],
//         ['D.Bergkamp', 'A.Winter'],
//         ['64', '76'],
//         stadiumsData.USA.cotton,
//         '63 500'
//       ),
//       new Match(
//         '10.07.1994',
//         stage[1_4],
//         ['Bulgaria', 'Germany'],
//         [[2, 1], [], []],
//         ['H.Stoichkov', 'Y.Letchkov'],
//         ['75', '78'],
//         ['L.Matthäus'],
//         ['47(p)'],
//         stadiumsData.USA.giants,
//         '72 416'
//       ),
//       new Match(
//         '10.07.1994',
//         stage[1_4],
//         ['Sweden', 'Romania'],
//         [
//           [1, 1],
//           [1, 1],
//           [5, 4],
//         ],
//         ['T.Brolin', 'K.Andersson'],
//         ['78', '115'],
//         ['F.Răducioiu'],
//         ['88, 101'],
//         stadiumsData.USA.stanford,
//         '83 500'
//       ),
//       new Match(
//         '13.07.1994',
//         stage[1_2],
//         ['Italy', 'Bulgaria'],
//         [[2, 1], [], []],
//         ['R.Baggio'],
//         ['21, 25'],
//         ['H.Stoichkov'],
//         ['44(p)'],
//         stadiumsData.USA.giants,
//         '74 110'
//       ),
//       new Match(
//         '13.07.1994',
//         stage[1_2],
//         ['Brazil', 'Sweden'],
//         [[1, 0], [], []],
//         ['Romário'],
//         ['80'],
//         [],
//         [],
//         stadiumsData.USA.rose,
//         '91 856'
//       ),
//       new Match(
//         '16.07.1994',
//         stage.place3,
//         ['Sweden', 'Bulgaria'],
//         [[4, 0], [], []],
//         ['T.Brolin', 'H.Mild', 'H.Larsson', 'K.Andersson'],
//         ['8', '30', '37', '39'],
//         [],
//         [],
//         stadiumsData.USA.rose,
//         '91 500'
//       ),
//       new Match(
//         '17.07.1994',
//         stage.final,
//         ['Brazil', 'Italy'],
//         [
//           [0, 0],
//           [0, 0],
//           [3, 2],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.USA.rose,
//         '94 194'
//       ),
//     ],
//     qualification: [],
//   },
//   1998: {
//     id: 'world-cup.16.1998',
//     title: '1998 FIFA World Cup',
//     date: '10 June - 12 July',
//     icon: logoWorldCup1998,
//     background: [backgroundFWC1998_1, backgroundFWC1998_2],
//     hostCountry: ['France'],
//     finalStage: [
//       new Match(
//         '10.06.1998',
//         stage.group.a,
//         ['Brazil', 'Scotland'],
//         [[2, 1], [], []],
//         ['César Sampaio', 'T.Boyd'],
//         ['5', '74(o.g.)'],
//         ['J.Collins'],
//         ['38(p)'],
//         stadiumsData.France.france,
//         '80 000'
//       ),
//       new Match(
//         '10.06.1998',
//         stage.group.a,
//         ['Morocco', 'Norway'],
//         [[2, 2], [], []],
//         ['M.Hadji', 'A.Hadda'],
//         ['37', '60'],
//         ['Y.Chippo', 'D.Eggen'],
//         ['45+1(o.g.)', '61'],
//         stadiumsData.France.mosson,
//         '29 800'
//       ),
//       new Match(
//         '16.06.1998',
//         stage.group.a,
//         ['Scotland', 'Norway'],
//         [[1, 1], [], []],
//         ['C.Burley'],
//         ['66'],
//         ['H.Flo'],
//         ['46'],
//         stadiumsData.France.lescure,
//         '31 800'
//       ),
//       new Match(
//         '16.06.1998',
//         stage.group.a,
//         ['Brazil', 'Morocco'],
//         [[3, 0], [], []],
//         ['Ronaldo', 'Rivaldo', 'Bebeto'],
//         ['9', '45+2', '50'],
//         [],
//         [],
//         stadiumsData.France.beaujoire,
//         '35 500'
//       ),
//       new Match(
//         '23.06.1998',
//         stage.group.a,
//         ['Morocco', 'Scotland'],
//         [[3, 0], [], []],
//         ['S.Bassir', 'A.Hadda'],
//         ['23, 85', '46'],
//         [],
//         [],
//         stadiumsData.France.geoffroyGuichard,
//         '30 600'
//       ),
//       new Match(
//         '23.06.1998',
//         stage.group.a,
//         ['Norway', 'Brazil'],
//         [[2, 1], [], []],
//         ['T.A.Flo', 'K.Rekdal'],
//         ['83', '89(p)'],
//         ['Bebeto'],
//         ['78'],
//         stadiumsData.France.velodrome,
//         '57 000'
//       ),
//       new Match(
//         '11.06.1998',
//         stage.group.b,
//         ['Italy', 'Chile'],
//         [[2, 2], [], []],
//         ['C.Vieri', 'R.Baggio'],
//         ['10', '84(p)'],
//         ['Marcelo Salas'],
//         ['45+3, 50'],
//         stadiumsData.France.lescure,
//         '31 800'
//       ),
//       new Match(
//         '11.06.1998',
//         stage.group.b,
//         ['Cameroon', 'Austria'],
//         [[1, 1], [], []],
//         ['P.Njanka'],
//         ['77'],
//         ['T.Polster'],
//         ['90+1'],
//         stadiumsData.France.toulouse,
//         '33 500'
//       ),
//       new Match(
//         '17.06.1998',
//         stage.group.b,
//         ['Chile', 'Austria'],
//         [[1, 1], [], []],
//         ['Marcelo Salas'],
//         ['70'],
//         ['I.Vastić'],
//         ['90+2'],
//         stadiumsData.France.geoffroyGuichard,
//         '30 600'
//       ),
//       new Match(
//         '17.06.1998',
//         stage.group.b,
//         ['Italy', 'Cameroon'],
//         [[3, 0], [], []],
//         ['L.Di Biagio', 'C.Vieri'],
//         ['7', '75, 89'],
//         [],
//         [],
//         stadiumsData.France.mosson,
//         '29 800'
//       ),
//       new Match(
//         '23.06.1998',
//         stage.group.b,
//         ['Italy', 'Austria'],
//         [[2, 1], [], []],
//         ['C.Vieri', 'R.Baggio'],
//         ['48', '90'],
//         ['A.Herzog'],
//         ['90+2'],
//         stadiumsData.France.france,
//         '80 000'
//       ),
//       new Match(
//         '23.06.1998',
//         stage.group.b,
//         ['Chile', 'Cameroon'],
//         [[1, 1], [], []],
//         ['J.Sierra'],
//         ['20'],
//         ['H.P.Mboma'],
//         ['56'],
//         stadiumsData.France.beaujoire,
//         '35 500'
//       ),
//       new Match(
//         '12.06.1998',
//         stage.group.c,
//         ['Denmark', 'Saudi Arabia'],
//         [[1, 0], [], []],
//         ['M.Rieper'],
//         ['69'],
//         [],
//         [],
//         stadiumsData.France.felixBollaert,
//         '38 100'
//       ),
//       new Match(
//         '12.06.1998',
//         stage.group.c,
//         ['France', 'South Africa'],
//         [[3, 0], [], []],
//         ['C.Dugarry', 'P.Issa', 'T.Henry'],
//         ['36', '77(o.g.)', '90+2'],
//         [],
//         [],
//         stadiumsData.France.velodrome,
//         '55 000'
//       ),
//       new Match(
//         '18.06.1998',
//         stage.group.c,
//         ['South Africa', 'Denmark'],
//         [[1, 1], [], []],
//         ['B.McCarthy'],
//         ['51'],
//         ['A.Nielsen'],
//         ['12'],
//         stadiumsData.France.toulouse,
//         '33 500'
//       ),
//       new Match(
//         '18.06.1998',
//         stage.group.c,
//         ['France', 'Saudi Arabia'],
//         [[4, 0], [], []],
//         ['T.Henry', 'D.Trezeguet', 'B.Lizarazu'],
//         ['37, 78', '68', '85'],
//         [],
//         [],
//         stadiumsData.France.france,
//         '80 000'
//       ),
//       new Match(
//         '24.06.1998',
//         stage.group.c,
//         ['France', 'Denmark'],
//         [[2, 1], [], []],
//         ['Y.Djorkaeff', 'E.Petit'],
//         ['12(p)', '56'],
//         ['M.Laudrup'],
//         ['42(p)'],
//         stadiumsData.France.gerland,
//         '39 100'
//       ),
//       new Match(
//         '24.06.1998',
//         stage.group.c,
//         ['South Africa', 'Saudi Arabia'],
//         [[2, 2], [], []],
//         ['S.Bartlett'],
//         ['18, 90+3(p)'],
//         ['Sami Al Jaber', 'Youssef Al Tunayan'],
//         ['45+2(p)', '74(p)'],
//         stadiumsData.France.lescure,
//         '31 800'
//       ),
//       new Match(
//         '12.06.1998',
//         stage.group.d,
//         ['Paraguay', 'Bulgaria'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.France.mosson,
//         '29 800'
//       ),
//       new Match(
//         '13.06.1998',
//         stage.group.d,
//         ['Nigeria', 'Spain'],
//         [[3, 2], [], []],
//         ['M.Adepoju', 'A.Zubizarreta', 'S.Oliseh'],
//         ['24', '73(o.g.)', '78'],
//         ['F.Hierro', 'Raúl'],
//         ['21', '47'],
//         stadiumsData.France.beaujoire,
//         '35 500'
//       ),
//       new Match(
//         '19.06.1998',
//         stage.group.d,
//         ['Nigeria', 'Bulgaria'],
//         [[1, 0], [], []],
//         ['V.Ikpeba'],
//         ['28'],
//         [],
//         [],
//         stadiumsData.France.parcDesPrinces,
//         '45 500'
//       ),
//       new Match(
//         '19.06.1998',
//         stage.group.d,
//         ['Spain', 'Paraguay'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.France.geoffroyGuichard,
//         '30 600'
//       ),
//       new Match(
//         '24.06.1998',
//         stage.group.d,
//         ['Paraguay', 'Nigeria'],
//         [[3, 1], [], []],
//         ['C.Ayala', 'M.Benitez', 'J.Cardozo'],
//         ['1', '58', '86'],
//         ['W.Oruma'],
//         ['11'],
//         stadiumsData.France.toulouse,
//         '33 500'
//       ),
//       new Match(
//         '24.06.1998',
//         stage.group.d,
//         ['Spain', 'Bulgaria'],
//         [[6, 1], [], []],
//         ['F.Hierro', 'Luis Enrique', 'F.Morientes', 'G.Bachev', 'Kiko'],
//         ['6(p)', '18', '55, 81', '88(o.g.)', '90+4'],
//         ['E.Kostadinov'],
//         ['58'],
//         stadiumsData.France.felixBollaert,
//         '38 100'
//       ),
//       new Match(
//         '13.06.1998',
//         stage.group.e,
//         ['Mexico', 'Korea Republic'],
//         [[3, 1], [], []],
//         ['R.Pelaez', 'Luis Hernandez'],
//         ['50', '75, 84'],
//         ['Ha Seok-ju'],
//         ['27'],
//         stadiumsData.France.gerland,
//         '39 100'
//       ),
//       new Match(
//         '13.06.1998',
//         stage.group.e,
//         ['Netherlands', 'Belgium'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.France.france,
//         '77 000'
//       ),
//       new Match(
//         '20.06.1998',
//         stage.group.e,
//         ['Belgium', 'Mexico'],
//         [[2, 2], [], []],
//         ['M.Wilmots'],
//         ['42, 47'],
//         ['García Aspe', 'C.Blanco'],
//         ['55(p)', '62'],
//         stadiumsData.France.lescure,
//         '31 800'
//       ),
//       new Match(
//         '20.06.1998',
//         stage.group.e,
//         ['Netherlands', 'Korea Republic'],
//         [[5, 0], [], []],
//         ['P.Cocu', 'M.Overmars', 'D.Bergkamp', 'P. van Hooijdonk', 'R. de Boer'],
//         ['37', '41', '71', '80', '83'],
//         [],
//         [],
//         stadiumsData.France.velodrome,
//         '55 000'
//       ),
//       new Match(
//         '25.06.1998',
//         stage.group.e,
//         ['Netherlands', 'Mexico'],
//         [[2, 2], [], []],
//         ['P.Cocu', 'R. de Boer'],
//         ['4', '18'],
//         ['R.Pelaez', 'Luis Hernandez'],
//         ['75', '90+4'],
//         stadiumsData.France.geoffroyGuichard,
//         '30 600'
//       ),
//       new Match(
//         '25.06.1998',
//         stage.group.e,
//         ['Belgium', 'Korea Republic'],
//         [[1, 1], [], []],
//         ['L.Nilis'],
//         ['7'],
//         ['Yoo Sang-chul'],
//         ['72'],
//         stadiumsData.France.parcDesPrinces,
//         '45 500'
//       ),
//       new Match(
//         '14.06.1998',
//         stage.group.f,
//         ['Serbia', 'Iran'],
//         [[1, 0], [], []],
//         ['S.Mihajlović'],
//         ['73'],
//         [],
//         [],
//         stadiumsData.France.geoffroyGuichard,
//         '30 600'
//       ),
//       new Match(
//         '15.06.1998',
//         stage.group.f,
//         ['Germany', 'United States'],
//         [[2, 0], [], []],
//         ['A.Möller', 'J.Klinsmann'],
//         ['9', '65'],
//         [],
//         [],
//         stadiumsData.France.parcDesPrinces,
//         '45 500'
//       ),
//       new Match(
//         '21.06.1998',
//         stage.group.f,
//         ['Germany', 'Serbia'],
//         [[2, 2], [], []],
//         ['S.Mihajlović', 'O.Bierhoff'],
//         ['72(o.g.)', '78'],
//         ['P.Mijatović', 'D.Stojković'],
//         ['13', '52'],
//         stadiumsData.France.felixBollaert,
//         '38 100'
//       ),
//       new Match(
//         '21.06.1998',
//         stage.group.f,
//         ['Iran', 'United States'],
//         [[2, 1], [], []],
//         ['H.Estili', 'M.Mahdavikia'],
//         ['40', '84'],
//         ['B.McBride'],
//         ['87'],
//         stadiumsData.France.gerland,
//         '39 100'
//       ),
//       new Match(
//         '25.06.1998',
//         stage.group.f,
//         ['Germany', 'Iran'],
//         [[2, 0], [], []],
//         ['O.Bierhoff', 'J.Klinsmann'],
//         ['50', '57'],
//         [],
//         [],
//         stadiumsData.France.mosson,
//         '29 800'
//       ),
//       new Match(
//         '25.06.1998',
//         stage.group.f,
//         ['Serbia', 'United States'],
//         [[1, 0], [], []],
//         ['S.Komljenović'],
//         ['4'],
//         [],
//         [],
//         stadiumsData.France.beaujoire,
//         '35 500'
//       ),
//       new Match(
//         '15.06.1998',
//         stage.group.g,
//         ['England', 'Tunisia'],
//         [[2, 0], [], []],
//         ['A.Shearer', 'P.Scholes'],
//         ['42', '89'],
//         [],
//         [],
//         stadiumsData.France.velodrome,
//         '54 587'
//       ),
//       new Match(
//         '15.06.1998',
//         stage.group.g,
//         ['Romania', 'Colombia'],
//         [[1, 0], [], []],
//         ['B.Ilie'],
//         ['45+1'],
//         [],
//         [],
//         stadiumsData.France.gerland,
//         '39 100'
//       ),
//       new Match(
//         '22.06.1998',
//         stage.group.g,
//         ['Colombia', 'Tunisia'],
//         [[1, 0], [], []],
//         ['L.Preciado'],
//         ['83'],
//         [],
//         [],
//         stadiumsData.France.mosson,
//         '29 800'
//       ),
//       new Match(
//         '22.06.1998',
//         stage.group.g,
//         ['Romania', 'England'],
//         [[2, 1], [], []],
//         ['V.Moldovan', 'D.Petrescu'],
//         ['46', '90'],
//         ['M.Owen'],
//         ['81'],
//         stadiumsData.France.toulouse,
//         '33 500'
//       ),
//       new Match(
//         '26.06.1998',
//         stage.group.g,
//         ['England', 'Colombia'],
//         [[2, 0], [], []],
//         ['D.Anderton', 'D.Beckham'],
//         ['20', '29'],
//         [],
//         [],
//         stadiumsData.France.felixBollaert,
//         '38 100'
//       ),
//       new Match(
//         '26.06.1998',
//         stage.group.g,
//         ['Romania', 'Tunisia'],
//         [[1, 1], [], []],
//         ['V.Moldovan'],
//         ['20', '29'],
//         ['S.Souayah'],
//         ['12(p)'],
//         stadiumsData.France.france,
//         '77 000'
//       ),
//       new Match(
//         '14.06.1998',
//         stage.group.h,
//         ['Argentina', 'Japan'],
//         [[1, 0], [], []],
//         ['G.Batistuta'],
//         ['28'],
//         [],
//         [],
//         stadiumsData.France.toulouse,
//         '33 500'
//       ),
//       new Match(
//         '14.06.1998',
//         stage.group.h,
//         ['Croatia', 'Jamaica'],
//         [[3, 1], [], []],
//         ['M.Stanić', 'R.Prosinečki', 'D.Šuker'],
//         ['27', '53', '69'],
//         ['R.Earle'],
//         ['45'],
//         stadiumsData.France.felixBollaert,
//         '38 100'
//       ),
//       new Match(
//         '20.06.1998',
//         stage.group.h,
//         ['Croatia', 'Japan'],
//         [[1, 0], [], []],
//         ['D.Šuker'],
//         ['77'],
//         [],
//         [],
//         stadiumsData.France.beaujoire,
//         '35 500'
//       ),
//       new Match(
//         '21.06.1998',
//         stage.group.h,
//         ['Argentina', 'Jamaica'],
//         [[5, 0], [], []],
//         ['A.Ortega', 'G.Batistuta'],
//         ['32, 55', '73, 78, 83(p)'],
//         [],
//         [],
//         stadiumsData.France.parcDesPrinces,
//         '45 500'
//       ),
//       new Match(
//         '26.06.1998',
//         stage.group.h,
//         ['Argentina', 'Croatia'],
//         [[1, 0], [], []],
//         ['M.Pineda'],
//         ['36'],
//         [],
//         [],
//         stadiumsData.France.lescure,
//         '31 800'
//       ),
//       new Match(
//         '26.06.1998',
//         stage.group.h,
//         ['Jamaica', 'Japan'],
//         [[2, 1], [], []],
//         ['T.Whitmore'],
//         ['39, 54'],
//         ['M.Nakayama'],
//         ['74'],
//         stadiumsData.France.gerland,
//         '39 100'
//       ),
//       new Match(
//         '27.06.1998',
//         stage[1_8],
//         ['Italy', 'Norway'],
//         [[1, 0], [], []],
//         ['C.Vieri'],
//         ['18'],
//         [],
//         [],
//         stadiumsData.France.velodrome,
//         '55 000'
//       ),
//       new Match(
//         '27.06.1998',
//         stage[1_8],
//         ['Brazil', 'Chile'],
//         [[4, 1], [], []],
//         ['Cesar Sampaio', 'Ronaldo'],
//         ['11, 26', '45+3(p), 72'],
//         ['Marcelo Salas'],
//         ['70'],
//         stadiumsData.France.parcDesPrinces,
//         '45 500'
//       ),
//       new Match(
//         '28.06.1998',
//         stage[1_8],
//         ['France', 'Paraguay'],
//         [[0, 0], [1, 0], []],
//         ['L.Blanc'],
//         ['114'],
//         [],
//         [],
//         stadiumsData.France.felixBollaert,
//         '31 800'
//       ),
//       new Match(
//         '28.06.1998',
//         stage[1_8],
//         ['Denmark', 'Nigeria'],
//         [[4, 1], [], []],
//         ['P.Møller', 'B.Laudrup', 'E.Sand', 'T.Helveg'],
//         ['3', '12', '58', '76'],
//         ['T.Babangida'],
//         ['77'],
//         stadiumsData.France.france,
//         '77 000'
//       ),
//       new Match(
//         '29.06.1998',
//         stage[1_8],
//         ['Germany', 'Mexico'],
//         [[2, 1], [], []],
//         ['J.Klinsmann', 'O.Bierhoff'],
//         ['74', '86'],
//         ['Luis Hernandez'],
//         ['47'],
//         stadiumsData.France.mosson,
//         '29 800'
//       ),
//       new Match(
//         '29.06.1998',
//         stage[1_8],
//         ['Netherlands', 'Serbia'],
//         [[2, 1], [], []],
//         ['D.Bergkamp', 'E.Davids'],
//         ['38', '90+2'],
//         ['S.Komljenović'],
//         ['48'],
//         stadiumsData.France.toulouse,
//         '33 500'
//       ),
//       new Match(
//         '30.06.1998',
//         stage[1_8],
//         ['Croatia', 'Romania'],
//         [[1, 0], [], []],
//         ['D.Šuker'],
//         ['45+2(p)'],
//         [],
//         [],
//         stadiumsData.France.lescure,
//         '31 800'
//       ),
//       new Match(
//         '30.06.1998',
//         stage[1_8],
//         ['Argentina', 'England'],
//         [
//           [2, 2],
//           [0, 0],
//           [4, 3],
//         ],
//         ['G.Batistuta', 'J.Zanetti'],
//         ['5(p)', '45+1'],
//         ['A.Shearer', 'M.Owen'],
//         ['9(p)', '16'],
//         stadiumsData.France.geoffroyGuichard,
//         '30 600'
//       ),
//       new Match(
//         '03.07.1998',
//         stage[1_4],
//         ['France', 'Italy'],
//         [
//           [0, 0],
//           [0, 0],
//           [4, 3],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.France.france,
//         '77 000'
//       ),
//       new Match(
//         '03.07.1998',
//         stage[1_4],
//         ['Brazil', 'Denmark'],
//         [[3, 2], [], []],
//         ['Bebeto', 'Rivaldo'],
//         ['10', '25, 59'],
//         ['M.Jørgensen', 'B.Laudrup'],
//         ['2', '50'],
//         stadiumsData.France.beaujoire,
//         '35 500'
//       ),
//       new Match(
//         '04.07.1998',
//         stage[1_4],
//         ['Netherlands', 'Argentina'],
//         [[2, 1], [], []],
//         ['P.Kluivert', 'D.Bergkamp'],
//         ['12', '90'],
//         ['Claudio López'],
//         ['17'],
//         stadiumsData.France.velodrome,
//         '55 000'
//       ),
//       new Match(
//         '04.07.1998',
//         stage[1_4],
//         ['Croatia', 'Germany'],
//         [[3, 0], [], []],
//         ['R.Jarni', 'G.Vlaović', 'D.Šuker'],
//         ['45+3', '80', '85'],
//         [],
//         [],
//         stadiumsData.France.gerland,
//         '39 100'
//       ),
//       new Match(
//         '07.07.1998',
//         stage[1_2],
//         ['Brazil', 'Netherlands'],
//         [
//           [1, 1],
//           [0, 0],
//           [4, 2],
//         ],
//         ['Ronaldo'],
//         ['46'],
//         ['P.Kluivert'],
//         ['87'],
//         stadiumsData.France.velodrome,
//         '54 000'
//       ),
//       new Match(
//         '08.07.1998',
//         stage[1_2],
//         ['France', 'Croatia'],
//         [[2, 1], [], []],
//         ['L.Thuram'],
//         ['47, 70'],
//         ['D.Šuker'],
//         ['46'],
//         stadiumsData.France.france,
//         '76 000'
//       ),
//       new Match(
//         '11.07.1998',
//         stage.place3,
//         ['Croatia', 'Netherlands'],
//         [[2, 1], [], []],
//         ['R.Prosinečki', 'D.Šuker'],
//         ['14', '36'],
//         ['B.Zenden'],
//         ['22'],
//         stadiumsData.France.parcDesPrinces,
//         '45 500'
//       ),
//       new Match(
//         '12.07.1998',
//         stage.final,
//         ['France', 'Brazil'],
//         [[3, 0], [], []],
//         ['Z.Zidane', 'E.Petit'],
//         ['27, 45+1', '90+3'],
//         [],
//         [],
//         stadiumsData.France.france,
//         '75 000'
//       ),
//     ],
//     qualification: [],
//   },
//   2002: {
//     id: 'world-cup.17.2002',
//     title: '2002 FIFA World Cup',
//     date: '31 May - 30 June',
//     icon: logoWorldCup2002,
//     background: [backgroundFWC2002_1, backgroundFWC2002_2],
//     hostCountry: ['Korea Republic', 'Japan'],
//     finalStage: [
//       new Match(
//         '31.05.2002',
//         stage.group.a,
//         ['Senegal', 'France'],
//         [[1, 0], [], []],
//         ['Bouba Diop'],
//         ['30'],
//         [],
//         [],
//         stadiumsData.SouthKorea.seoul,
//         '62 561'
//       ),
//       new Match(
//         '01.06.2002',
//         stage.group.a,
//         ['Denmark', 'Uruguay'],
//         [[2, 1], [], []],
//         ['J.D.Tomasson'],
//         ['45, 83'],
//         ['D.Rodríguez'],
//         ['47'],
//         stadiumsData.SouthKorea.ulsan,
//         '30 157'
//       ),
//       new Match(
//         '06.06.2002',
//         stage.group.a,
//         ['Denmark', 'Senegal'],
//         [[1, 1], [], []],
//         ['J.D.Tomasson'],
//         ['16(p)'],
//         ['S.Diao'],
//         ['52'],
//         stadiumsData.SouthKorea.daegu,
//         '43 500'
//       ),
//       new Match(
//         '06.06.2002',
//         stage.group.a,
//         ['France', 'Uruguay'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.SouthKorea.busan,
//         '38 289'
//       ),
//       new Match(
//         '11.06.2002',
//         stage.group.a,
//         ['Denmark', 'France'],
//         [[2, 0], [], []],
//         ['D.Rommedahl', 'J.D.Tomasson'],
//         ['22', '67'],
//         [],
//         [],
//         stadiumsData.SouthKorea.incheon,
//         '48 100'
//       ),
//       new Match(
//         '11.06.2002',
//         stage.group.a,
//         ['Senegal', 'Uruguay'],
//         [[3, 3], [], []],
//         ['K.Fadiga', 'Bouba Diop'],
//         ['20(p)', '26, 38'],
//         ['R.Morales', 'D.Forlán', 'A.Recoba'],
//         ['46', '69', '88(p)'],
//         stadiumsData.SouthKorea.suwon,
//         '33 681'
//       ),
//       new Match(
//         '02.06.2002',
//         stage.group.b,
//         ['Paraguay', 'South Africa'],
//         [[2, 2], [], []],
//         ['R.Santa Cruz', 'F.J. Arce Rolón'],
//         ['39', '55'],
//         ['T.Mokoena', 'Q.Fortune'],
//         ['63', '90+1(p)'],
//         stadiumsData.SouthKorea.busan,
//         '25 186'
//       ),
//       new Match(
//         '02.06.2002',
//         stage.group.b,
//         ['Spain', 'Slovenia'],
//         [[3, 1], [], []],
//         ['Raul', 'J.Carlos Valerón', 'F.Hierro'],
//         ['44', '74', '87(p)'],
//         ['S.Cimirotič'],
//         ['82'],
//         stadiumsData.SouthKorea.gwangju,
//         '28 598'
//       ),
//       new Match(
//         '07.06.2002',
//         stage.group.b,
//         ['Spain', 'Paraguay'],
//         [[3, 1], [], []],
//         ['F.Morientes', 'F.Hierro'],
//         ['53, 69', '83(p)'],
//         ['C.Puyol'],
//         ['10(o.g.)'],
//         stadiumsData.SouthKorea.jeonju,
//         '24 000'
//       ),
//       new Match(
//         '08.06.2002',
//         stage.group.b,
//         ['South Africa', 'Slovenia'],
//         [[1, 0], [], []],
//         ['S.Nomvethe'],
//         ['4'],
//         [],
//         [],
//         stadiumsData.SouthKorea.daegu,
//         '47 226'
//       ),
//       new Match(
//         '12.06.2002',
//         stage.group.b,
//         ['Spain', 'South Africa'],
//         [[3, 2], [], []],
//         ['Raul', 'G.Mendieta'],
//         ['4, 56', '45+1'],
//         ['B.McCarthy', 'L.Radebe'],
//         ['31', '53'],
//         stadiumsData.SouthKorea.daejeon,
//         '31 024'
//       ),
//       new Match(
//         '12.06.2002',
//         stage.group.b,
//         ['Paraguay', 'Slovenia'],
//         [[3, 1], [], []],
//         ['N.Cuevas', 'J.Campos'],
//         ['65, 84', '73'],
//         ['M.Ačimovič'],
//         ['45+1'],
//         stadiumsData.SouthKorea.jeju,
//         '30 176'
//       ),
//       new Match(
//         '03.06.2002',
//         stage.group.c,
//         ['Brazil', 'Turkey'],
//         [[2, 1], [], []],
//         ['Ronaldo', 'Rivaldo'],
//         ['50', '87(p)'],
//         ['Hasan Şaş'],
//         ['45+2'],
//         stadiumsData.SouthKorea.ulsan,
//         '33 842'
//       ),
//       new Match(
//         '04.06.2002',
//         stage.group.c,
//         ['Costa Rica', 'China'],
//         [[2, 0], [], []],
//         ['R.Gomez', 'M.Wright'],
//         ['61', '65'],
//         [],
//         [],
//         stadiumsData.SouthKorea.gwangju,
//         '27 217'
//       ),
//       new Match(
//         '08.06.2002',
//         stage.group.c,
//         ['Brazil', 'China'],
//         [[4, 0], [], []],
//         ['Roberto Carlos', 'Rivaldo', 'Ronaldinho', 'Ronaldo'],
//         ['15', '32', '45(p)', '55'],
//         [],
//         [],
//         stadiumsData.SouthKorea.jeju,
//         '36 750'
//       ),
//       new Match(
//         '09.06.2002',
//         stage.group.c,
//         ['Costa Rica', 'Turkey'],
//         [[1, 1], [], []],
//         ['W.Parks'],
//         ['86'],
//         ['Emre Belözoglu'],
//         ['56'],
//         stadiumsData.SouthKorea.incheon,
//         '42 299'
//       ),
//       new Match(
//         '13.06.2002',
//         stage.group.c,
//         ['Brazil', 'Costa Rica'],
//         [[5, 2], [], []],
//         ['Ronaldo', 'Edmilson', 'Rivaldo', 'Júnior'],
//         ['10, 13', '38', '62', '64'],
//         ['P.Wanchope', 'R.Gómez'],
//         ['39', '56'],
//         stadiumsData.SouthKorea.suwon,
//         '38 524'
//       ),
//       new Match(
//         '13.06.2002',
//         stage.group.c,
//         ['Turkey', 'China'],
//         [[3, 0], [], []],
//         ['Hasan Şaş', 'Bulent Korkmaz', 'Ü.Davala'],
//         ['6', '9', '62', '85'],
//         [],
//         [],
//         stadiumsData.SouthKorea.seoul,
//         '43 605'
//       ),
//       new Match(
//         '04.06.2002',
//         stage.group.d,
//         ['Korea Republic', 'Poland'],
//         [[2, 0], [], []],
//         ['Hwang Sun-hong', 'Yoo Sang-chul'],
//         ['26', '53'],
//         [],
//         [],
//         stadiumsData.SouthKorea.busan,
//         '48 760'
//       ),
//       new Match(
//         '05.06.2002',
//         stage.group.d,
//         ['United States', 'Portugal'],
//         [[3, 2], [], []],
//         ["J.O'Brien", 'J.Costa', 'B.McBride'],
//         ['4', '29(o.g.)', '36'],
//         ['Beto', 'J.Agoos'],
//         ['39', '71(o.g.)'],
//         stadiumsData.SouthKorea.suwon,
//         '37 306'
//       ),
//       new Match(
//         '10.06.2002',
//         stage.group.d,
//         ['Korea Republic', 'United States'],
//         [[1, 1], [], []],
//         ['Ahn Jung-hwan'],
//         ['78'],
//         ['C.Mathis'],
//         ['24'],
//         stadiumsData.SouthKorea.daegu,
//         '60 778'
//       ),
//       new Match(
//         '10.06.2002',
//         stage.group.d,
//         ['Portugal', 'Poland'],
//         [[4, 0], [], []],
//         ['Pedro Pauleta', 'Rui Costa'],
//         ['14, 65, 77', '88'],
//         [],
//         [],
//         stadiumsData.SouthKorea.jeonju,
//         '31 000'
//       ),
//       new Match(
//         '14.06.2002',
//         stage.group.d,
//         ['Korea Republic', 'Portugal'],
//         [[1, 0], [], []],
//         ['Park Ji-sung'],
//         ['70'],
//         [],
//         [],
//         stadiumsData.SouthKorea.incheon,
//         '50 239'
//       ),
//       new Match(
//         '14.06.2002',
//         stage.group.d,
//         ['Poland', 'United States'],
//         [[3, 1], [], []],
//         ['E.Olisadebe', 'P.Kryszałowicz', 'M.Żewłakow'],
//         ['3', '5', '66'],
//         ['L.Donovan'],
//         ['83'],
//         stadiumsData.SouthKorea.daejeon,
//         '26 482'
//       ),
//       new Match(
//         '01.06.2002',
//         stage.group.e,
//         ['Ireland', 'Cameroon'],
//         [[1, 1], [], []],
//         ['M.Holland'],
//         ['52'],
//         ["H.M'Boma"],
//         ['39'],
//         stadiumsData.Japan.niigata,
//         '33 679'
//       ),
//       new Match(
//         '01.06.2002',
//         stage.group.e,
//         ['Germany', 'Saudi Arabia'],
//         [[8, 0], [], []],
//         ['M.Klose', 'M.Ballack', 'C.Jancker', 'T.Linke', 'O.Bierhoff', 'B.Schneider'],
//         ['20, 25, 70', '40', '45+1', '73', '84', '90+1'],
//         [],
//         [],
//         stadiumsData.Japan.sapporo,
//         '32 218'
//       ),
//       new Match(
//         '05.06.2002',
//         stage.group.e,
//         ['Germany', 'Ireland'],
//         [[1, 1], [], []],
//         ['M.Klose'],
//         ['19'],
//         ['Robbie Keane'],
//         ['90+2'],
//         stadiumsData.Japan.kashima,
//         '35 854'
//       ),
//       new Match(
//         '06.06.2002',
//         stage.group.e,
//         ['Cameroon', 'Saudi Arabia'],
//         [[1, 0], [], []],
//         ["S.Eto'o"],
//         ['66'],
//         [],
//         [],
//         stadiumsData.Japan.saitama,
//         '52 328'
//       ),
//       new Match(
//         '11.06.2002',
//         stage.group.e,
//         ['Germany', 'Cameroon'],
//         [[2, 0], [], []],
//         ['M.Bode', 'M.Klose'],
//         ['50', '79'],
//         [],
//         [],
//         stadiumsData.Japan.shizuoka,
//         '47 085'
//       ),
//       new Match(
//         '11.06.2002',
//         stage.group.e,
//         ['Ireland', 'Saudi Arabia'],
//         [[3, 0], [], []],
//         ['Robbie Keane', 'G.Breen', 'D.Duff'],
//         ['7', '61', '87'],
//         [],
//         [],
//         stadiumsData.Japan.yokohama,
//         '65 320'
//       ),
//       new Match(
//         '02.06.2002',
//         stage.group.f,
//         ['Argentina', 'Nigeria'],
//         [[1, 0], [], []],
//         ['G.Batistuta'],
//         ['63'],
//         [],
//         [],
//         stadiumsData.Japan.kashima,
//         '34 050'
//       ),
//       new Match(
//         '02.06.2002',
//         stage.group.f,
//         ['England', 'Sweden'],
//         [[1, 1], [], []],
//         ['Sol Campbell'],
//         ['63'],
//         ['N.Alexandersson'],
//         ['59'],
//         stadiumsData.Japan.saitama,
//         '52 721'
//       ),
//       new Match(
//         '07.06.2002',
//         stage.group.f,
//         ['Sweden', 'Nigeria'],
//         [[2, 1], [], []],
//         ['H.Larsson'],
//         ['35, 63(p)'],
//         ['J.Aghahowa'],
//         ['27'],
//         stadiumsData.Japan.kobe,
//         '36 194'
//       ),
//       new Match(
//         '07.06.2002',
//         stage.group.f,
//         ['England', 'Argentina'],
//         [[1, 0], [], []],
//         ['D.Beckham'],
//         ['44(p)'],
//         [],
//         [],
//         stadiumsData.Japan.sapporo,
//         '35 927'
//       ),
//       new Match(
//         '12.06.2002',
//         stage.group.f,
//         ['Sweden', 'Argentina'],
//         [[1, 1], [], []],
//         ['A.Svensson'],
//         ['59'],
//         ['H.Crespo'],
//         ['88'],
//         stadiumsData.Japan.miyagi,
//         '45 777'
//       ),
//       new Match(
//         '12.06.2002',
//         stage.group.f,
//         ['Nigeria', 'England'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Japan.nagai,
//         '44 864'
//       ),
//       new Match(
//         '03.06.2002',
//         stage.group.g,
//         ['Mexico', 'Croatia'],
//         [[1, 0], [], []],
//         ['Cuauhtémoc Blanco'],
//         ['60(p)'],
//         [],
//         [],
//         stadiumsData.Japan.niigata,
//         '32 239'
//       ),
//       new Match(
//         '03.06.2002',
//         stage.group.g,
//         ['Italy', 'Ecuador'],
//         [[2, 0], [], []],
//         ['C.Vieri'],
//         ['7, 27'],
//         [],
//         [],
//         stadiumsData.Japan.sapporo,
//         '31 081'
//       ),
//       new Match(
//         '08.06.2002',
//         stage.group.g,
//         ['Croatia', 'Italy'],
//         [[2, 1], [], []],
//         ['I.Olić', 'M.Rapaić'],
//         ['73', '76'],
//         ['C.Vieri'],
//         ['55'],
//         stadiumsData.Japan.kashima,
//         '36 472'
//       ),
//       new Match(
//         '09.06.2002',
//         stage.group.g,
//         ['Mexico', 'Ecuador'],
//         [[2, 1], [], []],
//         ['J.Borgetti', 'Gerardo Torrado'],
//         ['28', '57'],
//         ['A.Delgado'],
//         ['5'],
//         stadiumsData.Japan.miyagi,
//         '45 610'
//       ),
//       new Match(
//         '13.06.2002',
//         stage.group.g,
//         ['Mexico', 'Italy'],
//         [[1, 1], [], []],
//         ['J.Borgetti'],
//         ['34'],
//         ['A.Del Piero'],
//         ['85'],
//         stadiumsData.Japan.oita,
//         '39 291'
//       ),
//       new Match(
//         '13.06.2002',
//         stage.group.g,
//         ['Ecuador', 'Croatia'],
//         [[1, 0], [], []],
//         ['É.Méndez'],
//         ['48'],
//         [],
//         [],
//         stadiumsData.Japan.yokohama,
//         '65 862'
//       ),
//       new Match(
//         '04.06.2002',
//         stage.group.h,
//         ['Japan', 'Belgium'],
//         [[2, 2], [], []],
//         ['T.Suzuki', 'J.Inamoto'],
//         ['59', '67'],
//         ['M.Wilmots', 'P.Van der Heyden'],
//         ['57', '75'],
//         stadiumsData.Japan.saitama,
//         '55 256'
//       ),
//       new Match(
//         '05.06.2002',
//         stage.group.h,
//         ['Russia', 'Tunisia'],
//         [[2, 0], [], []],
//         ['Y.Titov', 'V.Karpin'],
//         ['59', '64(p)'],
//         [],
//         [],
//         stadiumsData.Japan.kobe,
//         '30 957'
//       ),
//       new Match(
//         '09.06.2002',
//         stage.group.h,
//         ['Japan', 'Russia'],
//         [[1, 0], [], []],
//         ['J.Inamoto'],
//         ['51'],
//         [],
//         [],
//         stadiumsData.Japan.yokohama,
//         '66 108'
//       ),
//       new Match(
//         '10.06.2002',
//         stage.group.h,
//         ['Tunisia', 'Belgium'],
//         [[1, 1], [], []],
//         ['R.Bouzaiene'],
//         ['17'],
//         ['M.Wilmots'],
//         ['13'],
//         stadiumsData.Japan.oita,
//         '39 700'
//       ),
//       new Match(
//         '14.06.2002',
//         stage.group.h,
//         ['Japan', 'Tunisia'],
//         [[2, 0], [], []],
//         ['H.Morishima', 'H.Nakata'],
//         ['48', '75'],
//         [],
//         [],
//         stadiumsData.Japan.nagai,
//         '45 213'
//       ),
//       new Match(
//         '14.06.2002',
//         stage.group.h,
//         ['Belgium', 'Russia'],
//         [[3, 2], [], []],
//         ['J.Walem', 'W.Sonck', 'M.Wilmots'],
//         ['7', '78', '82'],
//         ['V.Beschastnykh', 'D.Sychev'],
//         ['52', '88'],
//         stadiumsData.Japan.shizuoka,
//         '46 640'
//       ),
//       new Match(
//         '15.06.2002',
//         stage[1_8],
//         ['Germany', 'Paraguay'],
//         [[1, 0], [], []],
//         ['O.Neuville'],
//         ['88'],
//         [],
//         [],
//         stadiumsData.SouthKorea.jeju,
//         '25 176'
//       ),
//       new Match(
//         '15.06.2002',
//         stage[1_8],
//         ['England', 'Denmark'],
//         [[3, 0], [], []],
//         ['R.Ferdinand', 'M.Owen', 'E.Heskey'],
//         ['5', '22', '44'],
//         [],
//         [],
//         stadiumsData.Japan.niigata,
//         '40 582'
//       ),
//       new Match(
//         '16.06.2002',
//         stage[1_8],
//         ['Senegal', 'Sweden'],
//         [[1, 1], [1, 0], []],
//         ['H.Camara'],
//         ['37', '104'],
//         ['H.Larsson'],
//         ['11'],
//         stadiumsData.Japan.oita,
//         '39 747'
//       ),
//       new Match(
//         '16.06.2002',
//         stage[1_8],
//         ['Spain', 'Ireland'],
//         [
//           [1, 1],
//           [0, 0],
//           [3, 2],
//         ],
//         ['F.Morientes'],
//         ['8'],
//         ['Robbie Keane'],
//         ['90(pen)'],
//         stadiumsData.SouthKorea.suwon,
//         '38 926'
//       ),
//       new Match(
//         '17.06.2002',
//         stage[1_8],
//         ['United States', 'Mexico'],
//         [[2, 0], [], []],
//         ['B.McBride', 'L.Donovan'],
//         ['8', '65'],
//         [],
//         [],
//         stadiumsData.SouthKorea.jeonju,
//         '36 380'
//       ),
//       new Match(
//         '17.06.2002',
//         stage[1_8],
//         ['Brazil', 'Belgium'],
//         [[2, 0], [], []],
//         ['Rivaldo', 'Ronaldo'],
//         ['67', '87'],
//         [],
//         [],
//         stadiumsData.Japan.kobe,
//         '40 440'
//       ),
//       new Match(
//         '18.06.2002',
//         stage[1_8],
//         ['Turkey', 'Japan'],
//         [[1, 0], [], []],
//         ['Ümit Davala'],
//         ['12'],
//         [],
//         [],
//         stadiumsData.Japan.miyagi,
//         '45 666'
//       ),
//       new Match(
//         '18.06.2002',
//         stage[1_8],
//         ['Korea Republic', 'Italy'],
//         [[1, 1], [1, 0], []],
//         ['Seol Ki-Hyeon', 'Ahn Jung-Hwan'],
//         ['88', '117'],
//         ['C.Vieri'],
//         ['18'],
//         stadiumsData.SouthKorea.daejeon,
//         '38 588'
//       ),
//       new Match(
//         '21.06.2002',
//         stage[1_4],
//         ['Brazil', 'England'],
//         [[2, 1], [], []],
//         ['Rivaldo', 'Ronaldinho'],
//         ['45+2', '50'],
//         ['M.Owen'],
//         ['23'],
//         stadiumsData.Japan.shizuoka,
//         '47 436'
//       ),
//       new Match(
//         '21.06.2002',
//         stage[1_4],
//         ['Germany', 'United States'],
//         [[1, 0], [], []],
//         ['M.Ballack'],
//         ['39'],
//         [],
//         [],
//         stadiumsData.SouthKorea.ulsan,
//         '37 337'
//       ),
//       new Match(
//         '22.06.2002',
//         stage[1_4],
//         ['Korea Republic', 'Spain'],
//         [
//           [0, 0],
//           [0, 0],
//           [5, 3],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.SouthKorea.gwangju,
//         '42 114'
//       ),
//       new Match(
//         '22.06.2002',
//         stage[1_4],
//         ['Turkey', 'Senegal'],
//         [[0, 0], [1, 0], []],
//         ['Ilhan Mansiz'],
//         ['94'],
//         [],
//         [],
//         stadiumsData.Japan.nagai,
//         '44 233'
//       ),
//       new Match(
//         '25.06.2002',
//         stage[1_2],
//         ['Germany', 'Korea Republic'],
//         [[1, 0], [], []],
//         ['M.Ballack'],
//         ['75'],
//         [],
//         [],
//         stadiumsData.SouthKorea.seoul,
//         '65 256'
//       ),
//       new Match(
//         '26.06.2002',
//         stage[1_2],
//         ['Brazil', 'Turkey'],
//         [[1, 0], [], []],
//         ['Ronaldo'],
//         ['49'],
//         [],
//         [],
//         stadiumsData.Japan.saitama,
//         '61 058'
//       ),
//       new Match(
//         '29.06.2002',
//         stage.place3,
//         ['Turkey', 'Korea Republic'],
//         [[3, 2], [], []],
//         ['Hakan Sukur', 'Ilhan Mansiz'],
//         ['1', '13, 32'],
//         ['Lee Eul-yong', 'Song Chong-gug'],
//         ['9', '90+3'],
//         stadiumsData.SouthKorea.daegu,
//         '63 483'
//       ),
//       new Match(
//         '30.06.2002',
//         stage.final,
//         ['Brazil', 'Germany'],
//         [[2, 0], [], []],
//         ['Ronaldo'],
//         ['67, 79'],
//         [],
//         [],
//         stadiumsData.Japan.yokohama,
//         '69 029'
//       ),
//     ],
//     qualification: [],
//   },
//   2006: {
//     id: 'world-cup.18.2006',
//     title: '2006 FIFA World Cup',
//     date: '9 June - 9 July',
//     icon: logoWorldCup2006,
//     background: [backgroundFWC2006_1, backgroundFWC2006_2],
//     hostCountry: ['Germany'],
//     finalStage: [
//       new Match(
//         '09.06.2006',
//         stage.group.a,
//         ['Germany', 'Costa Rica'],
//         [[4, 2], [], []],
//         ['Ph.Lahm', 'M.Klose', 'T.Frings'],
//         ['6', '17, 61', '87'],
//         ['Paulo Wanchope'],
//         ['12, 73'],
//         stadiumsData.Germany.allianz,
//         '66 000'
//       ),
//       new Match(
//         '09.06.2006',
//         stage.group.a,
//         ['Ecuador', 'Poland'],
//         [[2, 0], [], []],
//         ['C.Tenorio', 'A.Delgado'],
//         ['24', '80'],
//         [],
//         [],
//         stadiumsData.Germany.aufSchalke,
//         '52 000'
//       ),
//       new Match(
//         '14.06.2006',
//         stage.group.a,
//         ['Germany', 'Poland'],
//         [[1, 0], [], []],
//         ['O.Neuville'],
//         ['90+1'],
//         [],
//         [],
//         stadiumsData.Germany.westfalen,
//         '65 000'
//       ),
//       new Match(
//         '15.06.2006',
//         stage.group.a,
//         ['Ecuador', 'Costa Rica'],
//         [[3, 0], [], []],
//         ['C.Tenorio', 'A.Delgado', 'I.Kaviedes'],
//         ['8', '54', '90+2'],
//         [],
//         [],
//         stadiumsData.Germany.volkspark,
//         '50 000'
//       ),
//       new Match(
//         '20.06.2006',
//         stage.group.a,
//         ['Germany', 'Ecuador'],
//         [[3, 0], [], []],
//         ['M.Klose', 'L.Podolski'],
//         ['4, 44', '57'],
//         [],
//         [],
//         stadiumsData.Germany.olympiaB,
//         '72 000'
//       ),
//       new Match(
//         '20.06.2006',
//         stage.group.a,
//         ['Poland', 'Costa Rica'],
//         [[2, 1], [], []],
//         ['B.Bosacki'],
//         ['33, 65'],
//         ['R.Gomez'],
//         ['25'],
//         stadiumsData.Germany.niedersachsen,
//         '43 000'
//       ),
//       new Match(
//         '10.06.2006',
//         stage.group.b,
//         ['England', 'Paraguay'],
//         [[1, 0], [], []],
//         ['C.Gamarra'],
//         ['4(o.g.)'],
//         [],
//         [],
//         stadiumsData.Germany.wald,
//         '48 000'
//       ),
//       new Match(
//         '10.06.2006',
//         stage.group.b,
//         ['Trinidad & Tobago', 'Sweden'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.westfalen,
//         '62 959'
//       ),
//       new Match(
//         '15.06.2006',
//         stage.group.b,
//         ['England', 'Trinidad & Tobago'],
//         [[2, 0], [], []],
//         ['P.Crouch', 'S.Gerrard'],
//         ['83', '90+1'],
//         [],
//         [],
//         stadiumsData.Germany.easyCredit,
//         '41 000'
//       ),
//       new Match(
//         '15.06.2006',
//         stage.group.b,
//         ['Sweden', 'Paraguay'],
//         [[1, 0], [], []],
//         ['K.Ljungberg'],
//         ['89'],
//         [],
//         [],
//         stadiumsData.Germany.olympiaB,
//         '72 000'
//       ),
//       new Match(
//         '20.06.2006',
//         stage.group.b,
//         ['Sweden', 'England'],
//         [[2, 2], [], []],
//         ['M.Allbäck', 'H.Larsson'],
//         ['51', '90'],
//         ['J.Cole', 'S.Gerrard'],
//         ['34', '85'],
//         stadiumsData.Germany.rheinEnergie,
//         '45 000'
//       ),
//       new Match(
//         '20.06.2006',
//         stage.group.b,
//         ['Paraguay', 'Trinidad & Tobago'],
//         [[2, 0], [], []],
//         ['B.Sancho', 'N.Cuevas'],
//         ['25(o.g.)', '86'],
//         [],
//         [],
//         stadiumsData.Germany.fritzWalter,
//         '46 000'
//       ),
//       new Match(
//         '10.06.2006',
//         stage.group.c,
//         ['Argentina', 'Ivory Coast'],
//         [[2, 1], [], []],
//         ['H.Crespo', 'Javier Saviola'],
//         ['24', '38'],
//         ['D.Drogba'],
//         ['82'],
//         stadiumsData.Germany.volkspark,
//         '49 480'
//       ),
//       new Match(
//         '11.06.2006',
//         stage.group.c,
//         ['Netherlands', 'Serbia'],
//         [[1, 0], [], []],
//         ['A.Robben'],
//         ['18'],
//         [],
//         [],
//         stadiumsData.Germany.zentral,
//         '43 000'
//       ),
//       new Match(
//         '16.06.2006',
//         stage.group.c,
//         ['Argentina', 'Serbia'],
//         [[6, 0], [], []],
//         ['M.Rodríguez', 'E.Cambiasso', 'H.Crespo', 'Carlos Tévez', 'L.Messi'],
//         ['6, 41', '31', '78', '84', '88'],
//         [],
//         [],
//         stadiumsData.Germany.aufSchalke,
//         '52 000'
//       ),
//       new Match(
//         '16.06.2006',
//         stage.group.c,
//         ['Netherlands', 'Ivory Coast'],
//         [[2, 1], [], []],
//         ['R.van Persie', 'Ruud van Nistelrooy'],
//         ['24', '27'],
//         ['B.Koné'],
//         ['38'],
//         stadiumsData.Germany.daimler,
//         '52 000'
//       ),
//       new Match(
//         '21.06.2006',
//         stage.group.c,
//         ['Netherlands', 'Argentina'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.wald,
//         '48 000'
//       ),
//       new Match(
//         '21.06.2006',
//         stage.group.c,
//         ['Ivory Coast', 'Serbia'],
//         [[3, 2], [], []],
//         ['A.Dindane', 'B.Kalou'],
//         ['37(p), 67', '86(p)'],
//         ['N.Žigić', 'S.Ilić'],
//         ['10', '20'],
//         stadiumsData.Germany.allianz,
//         '66 000'
//       ),
//       new Match(
//         '11.06.2006',
//         stage.group.d,
//         ['Mexico', 'Iran'],
//         [[3, 1], [], []],
//         ['Omar Bravo', 'Sinha'],
//         ['28, 76', '79'],
//         ['Y.Golmohammadi'],
//         ['36'],
//         stadiumsData.Germany.easyCredit,
//         '41 000'
//       ),
//       new Match(
//         '11.06.2006',
//         stage.group.d,
//         ['Portugal', 'Angola'],
//         [[1, 0], [], []],
//         ['Pedro Pauleta'],
//         ['4'],
//         [],
//         [],
//         stadiumsData.Germany.rheinEnergie,
//         '45 000'
//       ),
//       new Match(
//         '16.06.2006',
//         stage.group.d,
//         ['Mexico', 'Angola'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.niedersachsen,
//         '43 000'
//       ),
//       new Match(
//         '17.06.2006',
//         stage.group.d,
//         ['Portugal', 'Iran'],
//         [[2, 0], [], []],
//         ['Deco', 'C.Ronaldo'],
//         ['63', '80(pen)'],
//         [],
//         [],
//         stadiumsData.Germany.wald,
//         '48 000'
//       ),
//       new Match(
//         '21.06.2006',
//         stage.group.d,
//         ['Portugal', 'Mexico'],
//         [[2, 1], [], []],
//         ['Maniche', 'Simão'],
//         ['6', '24(pen)'],
//         ['J.Fonseca'],
//         ['29'],
//         stadiumsData.Germany.aufSchalke,
//         '52 000'
//       ),
//       new Match(
//         '21.06.2006',
//         stage.group.d,
//         ['Iran', 'Angola'],
//         [[1, 1], [], []],
//         ['S.Bakhtiarizadeh'],
//         ['75'],
//         ['Flávio Amado'],
//         ['60'],
//         stadiumsData.Germany.zentral,
//         '38 000'
//       ),
//       new Match(
//         '12.06.2006',
//         stage.group.e,
//         ['Czech Republic', 'United States'],
//         [[3, 0], [], []],
//         ['J.Koller', 'T.Rosický'],
//         ['5', '36, 76'],
//         [],
//         [],
//         stadiumsData.Germany.aufSchalke,
//         '52 000'
//       ),
//       new Match(
//         '12.06.2006',
//         stage.group.e,
//         ['Italy', 'Ghana'],
//         [[2, 0], [], []],
//         ['A.Pirlo', 'V.Iaquinta'],
//         ['40', '83'],
//         [],
//         [],
//         stadiumsData.Germany.niedersachsen,
//         '43 000'
//       ),
//       new Match(
//         '17.06.2006',
//         stage.group.e,
//         ['Ghana', 'Czech Republic'],
//         [[2, 0], [], []],
//         ['A.Gyan', 'S.Muntari'],
//         ['2', '82'],
//         [],
//         [],
//         stadiumsData.Germany.rheinEnergie,
//         '45 000'
//       ),
//       new Match(
//         '17.06.2006',
//         stage.group.e,
//         ['Italy', 'United States'],
//         [[1, 1], [], []],
//         ['A.Gilardino'],
//         ['22'],
//         ['C.Zaccardo'],
//         ['27(o.g.)'],
//         stadiumsData.Germany.fritzWalter,
//         '46 000'
//       ),
//       new Match(
//         '22.06.2006',
//         stage.group.e,
//         ['Italy', 'Czech Republic'],
//         [[2, 0], [], []],
//         ['M.Materazzi', 'F.Inzaghi'],
//         ['26', '87'],
//         [],
//         [],
//         stadiumsData.Germany.volkspark,
//         '50 000'
//       ),
//       new Match(
//         '22.06.2006',
//         stage.group.e,
//         ['Ghana', 'United States'],
//         [[2, 1], [], []],
//         ['H.Draman', 'S.Appiah'],
//         ['22', '45+2(p)'],
//         ['C.Dempsey'],
//         ['43'],
//         stadiumsData.Germany.easyCredit,
//         '41 000'
//       ),
//       new Match(
//         '12.06.2006',
//         stage.group.f,
//         ['Australia', 'Japan'],
//         [[3, 1], [], []],
//         ['T.Cahill', 'J.Aloisi'],
//         ['84, 89', '90+2'],
//         ['S.Nakamura'],
//         ['26'],
//         stadiumsData.Germany.fritzWalter,
//         '46 000'
//       ),
//       new Match(
//         '13.06.2006',
//         stage.group.f,
//         ['Brazil', 'Croatia'],
//         [[1, 0], [], []],
//         ['Kaká'],
//         ['44'],
//         [],
//         [],
//         stadiumsData.Germany.olympiaM,
//         '72 000'
//       ),
//       new Match(
//         '18.06.2006',
//         stage.group.f,
//         ['Japan', 'Croatia'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.easyCredit,
//         '41 000'
//       ),
//       new Match(
//         '18.06.2006',
//         stage.group.f,
//         ['Brazil', 'Australia'],
//         [[2, 0], [], []],
//         ['Adriano', 'Fred'],
//         ['49', '90'],
//         [],
//         [],
//         stadiumsData.Germany.allianz,
//         '66 000'
//       ),
//       new Match(
//         '22.06.2006',
//         stage.group.f,
//         ['Brazil', 'Japan'],
//         [[4, 1], [], []],
//         ['Ronaldo', 'Juninho', 'Gilberto'],
//         ['45+1, 81', '53', '59'],
//         ['K.Tamada'],
//         ['34'],
//         stadiumsData.Germany.westfalen,
//         '65 000'
//       ),
//       new Match(
//         '22.06.2006',
//         stage.group.f,
//         ['Croatia', 'Australia'],
//         [[2, 2], [], []],
//         ['D.Srna', 'N.Kovač'],
//         ['2', '56'],
//         ['C.Moore', 'H.Kewell'],
//         ['38(p)', '79'],
//         stadiumsData.Germany.daimler,
//         '52 000'
//       ),
//       new Match(
//         '13.06.2006',
//         stage.group.g,
//         ['Korea Republic', 'Togo'],
//         [[2, 1], [], []],
//         ['Lee Chun-soo', 'Ahn Jung-hwan'],
//         ['54', '72'],
//         ['M.Kader Touré'],
//         ['31'],
//         stadiumsData.Germany.wald,
//         '48 000'
//       ),
//       new Match(
//         '13.06.2006',
//         stage.group.g,
//         ['France', 'Switzerland'],
//         [[0, 0], [], []],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.daimler,
//         '52 000'
//       ),
//       new Match(
//         '18.06.2006',
//         stage.group.g,
//         ['France', 'Korea Republic'],
//         [[1, 1], [], []],
//         ['T.Henry'],
//         ['9'],
//         ['Park Ji-sung'],
//         ['81'],
//         stadiumsData.Germany.zentral,
//         '43 000'
//       ),
//       new Match(
//         '19.06.2006',
//         stage.group.g,
//         ['Switzerland', 'Togo'],
//         [[2, 0], [], []],
//         ['A.Frei', 'T.Barnetta'],
//         ['16', '88'],
//         [],
//         [],
//         stadiumsData.Germany.westfalen,
//         '65 000'
//       ),
//       new Match(
//         '23.06.2006',
//         stage.group.g,
//         ['France', 'Togo'],
//         [[2, 0], [], []],
//         ['P.Vieira', 'T.Henry'],
//         ['55', '61'],
//         [],
//         [],
//         stadiumsData.Germany.rheinEnergie,
//         '45 000'
//       ),
//       new Match(
//         '23.06.2006',
//         stage.group.g,
//         ['Switzerland', 'Korea Republic'],
//         [[2, 0], [], []],
//         ['P.Senderos', 'A.Frei'],
//         ['23', '77'],
//         [],
//         [],
//         stadiumsData.Germany.niedersachsen,
//         '43 000'
//       ),
//       new Match(
//         '14.06.2006',
//         stage.group.h,
//         ['Spain', 'Ukraine'],
//         [[4, 0], [], []],
//         ['Xabi Alonso', 'D.Villa', 'F.Torres'],
//         ['13', '17, 48(p)', '81'],
//         [],
//         [],
//         stadiumsData.Germany.zentral,
//         '43 000'
//       ),
//       new Match(
//         '14.06.2006',
//         stage.group.h,
//         ['Tunisia', 'Saudi Arabia'],
//         [[2, 2], [], []],
//         ['Z.Jaziri', 'R.Jaïdi'],
//         ['23', '90+2'],
//         ['Yasser Al Qahtani', 'Sami Al Jaber'],
//         ['57', '84'],
//         stadiumsData.Germany.allianz,
//         '66 000'
//       ),
//       new Match(
//         '19.06.2006',
//         stage.group.h,
//         ['Ukraine', 'Saudi Arabia'],
//         [[4, 0], [], []],
//         ['A.Rusol', 'S.Rebrov', 'A.Shevchenko', 'M.Kalynychenko'],
//         ['4', '36', '46', '84'],
//         [],
//         [],
//         stadiumsData.Germany.volkspark,
//         '50 000'
//       ),
//       new Match(
//         '19.06.2006',
//         stage.group.h,
//         ['Spain', 'Tunisia'],
//         [[3, 1], [], []],
//         ['Raúl', 'F.Torres'],
//         ['71', '76, 90+1(p)'],
//         ['J.Mnari'],
//         ['8'],
//         stadiumsData.Germany.daimler,
//         '52 000'
//       ),
//       new Match(
//         '23.06.2006',
//         stage.group.h,
//         ['Spain', 'Saudi Arabia'],
//         [[1, 0], [], []],
//         ['Juanito'],
//         ['36'],
//         [],
//         [],
//         stadiumsData.Germany.fritzWalter,
//         '46 000'
//       ),
//       new Match(
//         '23.06.2006',
//         stage.group.h,
//         ['Ukraine', 'Tunisia'],
//         [[1, 0], [], []],
//         ['A.Shevchenko'],
//         ['70(p)'],
//         [],
//         [],
//         stadiumsData.Germany.olympiaB,
//         '72 000'
//       ),
//       new Match(
//         '24.06.2006',
//         stage[1_8],
//         ['Germany', 'Sweden'],
//         [[2, 0], [], []],
//         ['L.Podolski'],
//         ['4, 12'],
//         [],
//         [],
//         stadiumsData.Germany.allianz,
//         '66 000'
//       ),
//       new Match(
//         '24.06.2006',
//         stage[1_8],
//         ['Argentina', 'Mexico'],
//         [[1, 1], [1, 0], []],
//         ['H.Crespo', 'M.Rodríguez'],
//         ['10', '98'],
//         ['R.Márquez'],
//         ['6'],
//         stadiumsData.Germany.zentral,
//         '43 000'
//       ),
//       new Match(
//         '25.06.2006',
//         stage[1_8],
//         ['England', 'Ecuador'],
//         [[1, 0], [], []],
//         ['D.Beckham'],
//         ['60'],
//         [],
//         [],
//         stadiumsData.Germany.daimler,
//         '52 000'
//       ),
//       new Match(
//         '25.06.2006',
//         stage[1_8],
//         ['Portugal', 'Netherlands'],
//         [[1, 0], [], []],
//         ['Maniche'],
//         ['23'],
//         [],
//         [],
//         stadiumsData.Germany.easyCredit,
//         '41 000'
//       ),
//       new Match(
//         '26.06.2006',
//         stage[1_8],
//         ['Italy', 'Australia'],
//         [[1, 0], [], []],
//         ['F.Totti'],
//         ['90+5(p)'],
//         [],
//         [],
//         stadiumsData.Germany.fritzWalter,
//         '46 000'
//       ),
//       new Match(
//         '26.06.2006',
//         stage[1_8],
//         ['Ukraine', 'Switzerland'],
//         [
//           [0, 0],
//           [0, 0],
//           [3, 0],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.rheinEnergie,
//         '45 000'
//       ),
//       new Match(
//         '27.06.2006',
//         stage[1_8],
//         ['Brazil', 'Ghana'],
//         [[3, 0], [], []],
//         ['Ronaldo', 'Adriano', 'Zé Roberto'],
//         ['5', '45+1', '84'],
//         [],
//         [],
//         stadiumsData.Germany.westfalen,
//         '65 000'
//       ),
//       new Match(
//         '27.06.2006',
//         stage[1_8],
//         ['France', 'Spain'],
//         [[3, 1], [], []],
//         ['F.Ribéry', 'P.Vieira', 'Z.Zidane'],
//         ['41', '83', '90+2'],
//         ['D.Villa'],
//         ['28(p)'],
//         stadiumsData.Germany.niedersachsen,
//         '43 000'
//       ),
//       new Match(
//         '30.06.2006',
//         stage[1_4],
//         ['Germany', 'Argentina'],
//         [
//           [1, 1],
//           [0, 0],
//           [4, 2],
//         ],
//         ['M.Klose'],
//         ['80'],
//         ['R.F.Ayala'],
//         ['49'],
//         stadiumsData.Germany.olympiaB,
//         '72 000'
//       ),
//       new Match(
//         '30.06.2006',
//         stage[1_4],
//         ['Italy', 'Ukraine'],
//         [[3, 0], [], []],
//         ['G.Zambrotta', 'L.Toni'],
//         ['6', '59, 69'],
//         [],
//         [],
//         stadiumsData.Germany.volkspark,
//         '50 000'
//       ),
//       new Match(
//         '01.07.2006',
//         stage[1_4],
//         ['Portugal', 'England'],
//         [
//           [0, 0],
//           [0, 0],
//           [3, 1],
//         ],
//         [],
//         [],
//         [],
//         [],
//         stadiumsData.Germany.aufSchalke,
//         '52 000'
//       ),
//       new Match(
//         '01.07.2006',
//         stage[1_4],
//         ['France', 'Brazil'],
//         [[1, 0], [], []],
//         ['T.Henry'],
//         ['57'],
//         [],
//         [],
//         stadiumsData.Germany.wald,
//         '48 000'
//       ),
//       new Match(
//         '04.07.2006',
//         stage[1_2],
//         ['Italy', 'Germany'],
//         [[0, 0], [2, 0], []],
//         ['F.Grosso', 'A.Del Piero'],
//         ['119', '120+1'],
//         [],
//         [],
//         stadiumsData.Germany.westfalen,
//         '65 000'
//       ),
//       new Match(
//         '05.07.2006',
//         stage[1_2],
//         ['France', 'Portugal'],
//         [[1, 0], [], []],
//         ['Z.Zidane'],
//         ['33(p)'],
//         [],
//         [],
//         stadiumsData.Germany.allianz,
//         '66 000'
//       ),
//       new Match(
//         '08.07.2006',
//         stage.place3,
//         ['Germany', 'Portugal'],
//         [[3, 1], [], []],
//         ['B.Schweinsteiger', 'Petit'],
//         ['56, 78', '60(o.g.)'],
//         ['Nuno Gomes'],
//         ['88'],
//         stadiumsData.Germany.daimler,
//         '52 000'
//       ),
//       new Match(
//         '09.07.2006',
//         stage.final,
//         ['Italy', 'France'],
//         [
//           [1, 1],
//           [0, 0],
//           [5, 3],
//         ],
//         ['M.Materazzi'],
//         ['19'],
//         ['Z.Zidane'],
//         ['7(p)'],
//         stadiumsData.Germany.olympiaB,
//         '69 000'
//       ),
//     ],
//     qualification: [],
//   },
//   2010: {
//     id: 'world-cup.19.2010',
//     title: '2010 FIFA World Cup',
//     date: '11 June - 11 July',
//     icon: logoWorldCup2010,
//     background: [],
//     hostCountry: ['South Africa'],
//     finalStage: [],
//     qualification: [],
//   },
//   2014: {
//     id: 'world-cup.20.2014',
//     title: '2014 FIFA World Cup',
//     date: '12 June - 13 July',
//     icon: logoWorldCup2014,
//     background: [],
//     hostCountry: ['Brazil'],
//     finalStage: [],
//     qualification: [],
//   },
//   2018: {
//     id: 'world-cup.21.2018',
//     title: '2018 FIFA World Cup',
//     date: '14 June - 15 July',
//     icon: logoWorldCup2018,
//     background: [],
//     hostCountry: ['Russia'],
//     finalStage: [],
//     qualification: [],
//   },
//   2022: {
//     id: 'world-cup.22.2022',
//     title: '2022 FIFA World Cup',
//     date: '20 November - 18 December',
//     icon: logoWorldCup2022,
//     background: [],
//     hostCountry: ['Qatar'],
//     finalStage: [],
//     qualification: [],
//   },
}
