export const STAGES = {
  FINAL: '1:final',
  FINAL_GROUP_ROUND: 'group Final round: final',
  THIRD_PLACE: '2:third place play-off',
  THIRD_PLACE_GROUP_ROUND: 'group Final round: third place',
  SEMI_FINAL: '3:semi-final',
  QUARTER_FINAL: '4:quarter-finals',
  ROUND_OF_16: '5:round of 16',
  ROUND_OF_32: '6:round of 32',
  GROUP_1: 'group 1',
  GROUP_2: 'group 2',
  GROUP_3: 'group 3',
  GROUP_4: 'group 4',
  GROUP_5: 'group 5',
  GROUP_6: 'group 6',
  GROUP_7: 'group 7',
  GROUP_8: 'group 8',
  GROUP_A: 'group A',
  GROUP_B: 'group B',
  GROUP_C: 'group C',
  GROUP_D: 'group D',
  GROUP_E: 'group E',
  GROUP_F: 'group F',
  GROUP_G: 'group G',
  GROUP_H: 'group H',
  FINAL_GROUP: 'group Final round',
  SECOND_GROUP_ROUND_A: 'group A (second round)',
  SECOND_GROUP_ROUND_B: 'group B (second round)',
  SECOND_GROUP_ROUND_C: 'group C (second round)',
  SECOND_GROUP_ROUND_D: 'group D (second round)',
} as const

// С as const TypeScript видит точные значения: { readonly FINAL: "1:final" }
// вместо { FINAL: string }
