import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { NationalTeamsState } from '../types'
import { Team } from '@/entities/team'
import {
  teamAlbania,
  teamAndorra,
  teamArmenia,
  teamAustria,
  teamAzerbaijan,
  teamBelarus,
  teamBelgium,
  teamBosniaAndHerzegovina,
  teamBulgaria,
  teamCroatia,
  teamCyprus,
  teamCzechoslovakia,
  teamCzechRepublic,
  teamDenmark,
  teamEastGermany,
  teamEngland,
  teamEstonia,
  teamFaroeIslands,
  teamFinland,
  teamFrance,
  teamGeorgia,
  teamGermany,
  teamGibraltar,
  teamGreece,
  teamHungary,
  teamIceland,
  teamIreland,
  teamIsrael,
  teamItaly,
  teamKazakhstan,
  teamKosovo,
  teamLatvia,
  teamLiechtenstein,
  teamLithuania,
  teamLuxembourg,
  teamMalta,
  teamMoldova,
  teamMontenegro,
  teamNetherlands,
  teamNorthIreland,
  teamNorthMacedonia,
  teamNorway,
  teamPoland,
  teamPortugal,
  teamRomania,
  teamRussia,
  teamSanMarino,
  teamScotland,
  teamSerbia,
  teamSlovakia,
  teamSlovenia,
  teamSovietUnion,
  teamSpain,
  teamSweden,
  teamSwitzerland,
  teamTurkey,
  teamUkraine,
  teamWales,
  teamYugoslavia,
} from '@/entities/team/model/data/uefa'
import {
  teamAustralia,
  teamBrunei,
  teamCambodia,
  teamTimorLeste,
  teamIndonesia,
  teamLaos,
  teamMalaysia,
  teamMyanmar,
  teamPhilippines,
  teamSingapore,
  teamThailand,
  teamVietnam,
  teamAfghanistan,
  teamIran,
  teamKyrgyzRepublic,
  teamTajikistan,
  teamTurkmenistan,
  teamUzbekistan,
  teamChina,
  teamTaiwan,
  teamDPRKorea,
  teamGuam,
  teamHongKong,
  teamJapan,
  teamKoreaRepublic,
  teamMacau,
  teamMongolia,
  teamNorthernMarianaIslands,
  teamBangladesh,
  teamBhutan,
  teamIndia,
  teamMaldives,
  teamNepal,
  teamPakistan,
  teamSriLanka,
  teamBahrain,
  teamIraq,
  teamJordan,
  teamKuwait,
  teamLebanon,
  teamOman,
  teamPalestine,
  teamQatar,
  teamSaudiArabia,
  teamSyria,
  teamUAEmirates,
  teamYemen,
} from '@/entities/team/model/data/afc'
import {
  teamAlgeria,
  teamEgypt,
  teamLibya,
  teamMorocco,
  teamTunisia,
  teamBenin,
  teamBurkinaFaso,
  teamCapeVerde,
  teamGambia,
  teamGhana,
  teamGuinea,
  teamGuineaBissau,
  teamIvoryCoast,
  teamLiberia,
  teamMali,
  teamMauritania,
  teamNiger,
  teamNigeria,
  teamSenegal,
  teamSierraLeone,
  teamTogo,
  teamCameroon,
  teamCentralAfricanRepublic,
  teamChad,
  teamCongo,
  teamDRCongo,
  teamEquatorialGuinea,
  teamGabon,
  teamSaoTomeAndPrincipe,
  teamBurundi,
  teamDjibouti,
  teamEritrea,
  teamEthiopia,
  teamKenya,
  teamRwanda,
  teamSomalia,
  teamSouthSudan,
  teamSudan,
  teamTanzania,
  teamUganda,
  teamZanzibar,
  teamAngola,
  teamBotswana,
  teamComoros,
  teamEswatini,
  teamLesotho,
  teamMadagascar,
  teamMalawi,
  teamMauritius,
  teamMozambique,
  teamNamibia,
  teamSeychelles,
  teamSouthAfrica,
  teamZambia,
  teamZimbabwe,
  teamReunion,
} from '@/entities/team/model/data/caf'
import {
  teamCanada,
  teamMexico,
  teamUnitedStates,
  teamBelize,
  teamCostaRica,
  teamElSalvador,
  teamGuatemala,
  teamHonduras,
  teamNicaragua,
  teamPanama,
  teamAnguilla,
  teamAntiguaAndBarbuda,
  teamAruba,
  teamBahamas,
  teamBarbados,
  teamBermuda,
  teamBonaire,
  teamBritishVirginIslands,
  teamCaymanIslands,
  teamCuba,
  teamCuracao,
  teamDominica,
  teamDominicanRepublic,
  teamFrenchGuiana,
  teamGrenada,
  teamGuadeloupe,
  teamGuyana,
  teamHaiti,
  teamJamaica,
  teamMartinique,
  teamMontserrat,
  teamPuertoRico,
  teamSaintKittsAndNevis,
  teamSaintLucia,
  teamSaintMartin,
  teamSaintVincentAndTheGrenadines,
  teamSintMaarten,
  teamSuriname,
  teamTrinidadAndTobago,
  teamTurksAndCaicosIslands,
  teamUSVirginIslands,
} from '@/entities/team/model/data/concacaf'
import {
  teamArgentina,
  teamBolivia,
  teamBrazil,
  teamChile,
  teamColombia,
  teamEcuador,
  teamParaguay,
  teamPeru,
  teamUruguay,
  teamVenezuela,
} from '@/entities/team/model/data/conmebol'
import {
  teamAmericanSamoa,
  teamCookIslands,
  teamFiji,
  teamKiribati,
  teamNewCaledonia,
  teamNewZealand,
  teamPapuaNewGuinea,
  teamSamoa,
  teamSolomonIslands,
  teamTahiti,
  teamTonga,
  teamTuvalu,
  teamVanuatu,
} from '@/entities/team/model/data/ofc'
import { Country } from '@/shared/types'

const initialState: NationalTeamsState = {
  teams: {
    Germany: teamGermany,
    England: teamEngland,
    Italy: teamItaly,
    Spain: teamSpain,
    France: teamFrance,
    Albania: teamAlbania,
    Andorra: teamAndorra,
    Armenia: teamArmenia,
    Austria: teamAustria,
    Azerbaijan: teamAzerbaijan,
    Belarus: teamBelarus,
    Belgium: teamBelgium,
    'Bosnia and Herzegovina': teamBosniaAndHerzegovina,
    Bulgaria: teamBulgaria,
    Croatia: teamCroatia,
    Cyprus: teamCyprus,
    'Czech Republic': teamCzechRepublic,
    Denmark: teamDenmark,
    Estonia: teamEstonia,
    'Faroe Islands': teamFaroeIslands,
    Finland: teamFinland,
    Greece: teamGreece,
    Gibraltar: teamGibraltar,
    Georgia: teamGeorgia,
    Hungary: teamHungary,
    Iceland: teamIceland,
    Israel: teamIsrael,
    Kazakhstan: teamKazakhstan,
    Kosovo: teamKosovo,
    Latvia: teamLatvia,
    Liechtenstein: teamLiechtenstein,
    Lithuania: teamLithuania,
    Luxembourg: teamLuxembourg,
    Malta: teamMalta,
    Moldova: teamMoldova,
    Montenegro: teamMontenegro,
    Netherlands: teamNetherlands,
    'North Macedonia': teamNorthMacedonia,
    'North. Ireland': teamNorthIreland,
    Norway: teamNorway,
    Poland: teamPoland,
    Portugal: teamPortugal,
    Ireland: teamIreland,
    Romania: teamRomania,
    Russia: teamRussia,
    'San Marino': teamSanMarino,
    Scotland: teamScotland,
    Serbia: teamSerbia,
    Slovakia: teamSlovakia,
    Slovenia: teamSlovenia,
    Sweden: teamSweden,
    Switzerland: teamSwitzerland,
    Turkey: teamTurkey,
    Ukraine: teamUkraine,
    Wales: teamWales,
    Yugoslavia: teamYugoslavia,
    Czechoslovakia: teamCzechoslovakia,
    'Soviet Union': teamSovietUnion,
    'East Germany': teamEastGermany,

    Algeria: teamAlgeria,
    Egypt: teamEgypt,
    Libya: teamLibya,
    Morocco: teamMorocco,
    Tunisia: teamTunisia,
    Benin: teamBenin,
    'Burkina Faso': teamBurkinaFaso,
    'Cape Verde': teamCapeVerde,
    Gambia: teamGambia,
    Ghana: teamGhana,
    Guinea: teamGuinea,
    'Guinea-Bissau': teamGuineaBissau,
    'Ivory Coast': teamIvoryCoast,
    Liberia: teamLiberia,
    Mali: teamMali,
    Mauritania: teamMauritania,
    Niger: teamNiger,
    Nigeria: teamNigeria,
    Senegal: teamSenegal,
    'Sierra Leone': teamSierraLeone,
    Togo: teamTogo,
    Cameroon: teamCameroon,
    'Central African Republic': teamCentralAfricanRepublic,
    Chad: teamChad,
    Congo: teamCongo,
    'DR Congo': teamDRCongo,
    'Equatorial Guinea': teamEquatorialGuinea,
    Gabon: teamGabon,
    'Sao Tome and Principe': teamSaoTomeAndPrincipe,
    Burundi: teamBurundi,
    Djibouti: teamDjibouti,
    Eritrea: teamEritrea,
    Ethiopia: teamEthiopia,
    Kenya: teamKenya,
    Rwanda: teamRwanda,
    Somalia: teamSomalia,
    'South Sudan': teamSouthSudan,
    Sudan: teamSudan,
    Tanzania: teamTanzania,
    Uganda: teamUganda,
    Zanzibar: teamZanzibar,
    Angola: teamAngola,
    Botswana: teamBotswana,
    Comoros: teamComoros,
    Eswatini: teamEswatini,
    Lesotho: teamLesotho,
    Madagascar: teamMadagascar,
    Malawi: teamMalawi,
    Mauritius: teamMauritius,
    Mozambique: teamMozambique,
    Namibia: teamNamibia,
    Seychelles: teamSeychelles,
    'South Africa': teamSouthAfrica,
    Zambia: teamZambia,
    Zimbabwe: teamZimbabwe,
    Reunion: teamReunion,

    Australia: teamAustralia,
    Brunei: teamBrunei,
    Cambodia: teamCambodia,
    'Timor-Leste': teamTimorLeste,
    Indonesia: teamIndonesia,
    Laos: teamLaos,
    Malaysia: teamMalaysia,
    Myanmar: teamMyanmar,
    Philippines: teamPhilippines,
    Singapore: teamSingapore,
    Thailand: teamThailand,
    Vietnam: teamVietnam,
    Afghanistan: teamAfghanistan,
    Iran: teamIran,
    'Kyrgyz Republic': teamKyrgyzRepublic,
    Tajikistan: teamTajikistan,
    Turkmenistan: teamTurkmenistan,
    Uzbekistan: teamUzbekistan,
    China: teamChina,
    Taiwan: teamTaiwan,
    'DPR Korea': teamDPRKorea,
    Guam: teamGuam,
    'Hong Kong': teamHongKong,
    Japan: teamJapan,
    'Korea Republic': teamKoreaRepublic,
    Macau: teamMacau,
    Mongolia: teamMongolia,
    'Northern Mariana Islands': teamNorthernMarianaIslands,
    Bangladesh: teamBangladesh,
    Bhutan: teamBhutan,
    India: teamIndia,
    Maldives: teamMaldives,
    Nepal: teamNepal,
    Pakistan: teamPakistan,
    'Sri Lanka': teamSriLanka,
    Bahrain: teamBahrain,
    Iraq: teamIraq,
    Jordan: teamJordan,
    Kuwait: teamKuwait,
    Lebanon: teamLebanon,
    Oman: teamOman,
    Palestine: teamPalestine,
    Qatar: teamQatar,
    'Saudi Arabia': teamSaudiArabia,
    Syria: teamSyria,
    'U.A. Emirates': teamUAEmirates,
    Yemen: teamYemen,

    Canada: teamCanada,
    Mexico: teamMexico,
    'United States': teamUnitedStates,
    Belize: teamBelize,
    'Costa Rica': teamCostaRica,
    'El Salvador': teamElSalvador,
    Guatemala: teamGuatemala,
    Honduras: teamHonduras,
    Nicaragua: teamNicaragua,
    Panama: teamPanama,
    Anguilla: teamAnguilla,
    'Antigua and Barbuda': teamAntiguaAndBarbuda,
    Aruba: teamAruba,
    Bahamas: teamBahamas,
    Barbados: teamBarbados,
    Bermuda: teamBermuda,
    Bonaire: teamBonaire,
    'British Virgin Islands': teamBritishVirginIslands,
    'Cayman Islands': teamCaymanIslands,
    Cuba: teamCuba,
    Curacao: teamCuracao,
    Dominica: teamDominica,
    'Dominican Republic': teamDominicanRepublic,
    'French Guiana': teamFrenchGuiana,
    Grenada: teamGrenada,
    Guadeloupe: teamGuadeloupe,
    Guyana: teamGuyana,
    Haiti: teamHaiti,
    Jamaica: teamJamaica,
    Martinique: teamMartinique,
    Montserrat: teamMontserrat,
    'Puerto Rico': teamPuertoRico,
    'Saint Kitts and Nevis': teamSaintKittsAndNevis,
    'Saint Lucia': teamSaintLucia,
    'Saint Martin': teamSaintMartin,
    'Saint Vincent and the Grenadines': teamSaintVincentAndTheGrenadines,
    'Sint Maarten': teamSintMaarten,
    Suriname: teamSuriname,
    'Trinidad & Tobago': teamTrinidadAndTobago,
    'Turks and Caicos Islands': teamTurksAndCaicosIslands,
    'U.S. Virgin Islands': teamUSVirginIslands,

    'American Samoa': teamAmericanSamoa,
    'Cook Islands': teamCookIslands,
    Fiji: teamFiji,
    Kiribati: teamKiribati,
    'New Caledonia': teamNewCaledonia,
    'New Zealand': teamNewZealand,
    'Papua New Guinea': teamPapuaNewGuinea,
    Samoa: teamSamoa,
    'Solomon Islands': teamSolomonIslands,
    Tahiti: teamTahiti,
    Tonga: teamTonga,
    Tuvalu: teamTuvalu,
    Vanuatu: teamVanuatu,

    Argentina: teamArgentina,
    Bolivia: teamBolivia,
    Brazil: teamBrazil,
    Chile: teamChile,
    Colombia: teamColombia,
    Ecuador: teamEcuador,
    Paraguay: teamParaguay,
    Peru: teamPeru,
    Uruguay: teamUruguay,
    Venezuela: teamVenezuela,
  },
  isLoading: false,
  error: null,
}

const teamsSlice = createSlice({
  name: 'nationalTeams',
  initialState,
  reducers: {
    setTeams: (state, action: PayloadAction<Record<string, Team>>) => {
      state.teams = action.payload
    },
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.isLoading = action.payload
    },
    setError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload
    },
    updateTeam: (
      state,
      action: PayloadAction<{ country: Country; team: Team }>
    ) => {
      state.teams[action.payload.country] = action.payload.team
    },
  },
})

export const { setTeams, setLoading, setError, updateTeam } =
  teamsSlice.actions
export default teamsSlice.reducer
