export const PATH = {
  home: '/',
  about: '/about',
  tournaments: '/tournaments',
  teams: '/teams',
  clubs: '/clubs',
  rating: '/rating',

  worldCup: '/tournaments/world-cup',
  confederationsCup: '/tournaments/confederations-cup',
  clubWorldCup: '/tournaments/club-world-cup',
  euro: '/tournaments/uefa-euro',
  uefaNationsLeague: '/tournaments/uefa-nations-league',
  conmebolCopaAmerica: '/tournaments/conmebol-copa-america',
  concacafGoldCup: '/tournaments/concacaf-gold-cup',
  concacafNationsLeague: '/tournaments/concacaf-nations-league',
  africaCupNations: '/tournaments/africa-cup-nations',
  africanNationsChampionship: '/tournaments/africa-nations-championship',
  afcAsianCup: '/tournaments/afc-asian-cup',
  ofcNationsCup: '/tournaments/ofc-nations-cup',

  uefaChampionsLeague: '/tournaments/uefa-champions-league',
  uefaEuropaLeague: '/tournaments/uefa-europa-league',
  uefaConferenceLeague: '/tournamclub/uefa-conference-league',
  uefaSuperLeague: '/tournaments/uefa-super-league',
  uefaCupWinnersCup: '/tournaments/uefa-cup-winners-cup',
  uefaIntertotoCup: '/tournaments/uefa-cup-intertoto-cup',
  uefaInterCitiesFairsCup: '/tournaments/uefa-inter-cities-fairs-cup',
  conmebolCopaLibertadores: '/tournaments/conmebol-copa-libertadores',
  conmebolCopaSudamericana: '/tournaments/conmebol-copa-sudamericana',
  conmebolRecopaSudamericana: '/tournaments/conmebol-recopa-sudamericana',
  concacafChampionsCup: '/tournaments/concacaf-champions-cup',
  cafChampionsLeague: '/tournaments/caf-champions-league',
  cafConfederationCup: '/tournaments/caf-confederation-cup',
  cafSuperCup: '/tournaments/caf-super-cup',
  afcChampionsLeagueElite: '/tournaments/afc-champions-league-elite',
  afcChampionsLeagueTwo: '/tournaments/afc-champions-league-two',
  afcSuperCup: '/tournaments/afc-super-cup',
  ofcChampionsLeague: '/tournaments/ofc-champions-league',
}
