import { TournamentStages } from './types'

export const tournamentStages: TournamentStages = {
  final: '1:final',
  finalGroupRound: 'group Final round: final',
  thirdPlace: '2:third place play-off',
  thirdPlaceGroupRound: 'group Final round: third place',
  semiFinal: '3:semi-final',
  quarterFinal: '4:quarter-finals',
  roundOf16: '5:round of 16',
  roundOf32: '6:round of 32',
  group1: 'group 1',
  group2: 'group 2',
  group3: 'group 3',
  group4: 'group 4',
  group5: 'group 5',
  group6: 'group 6',
  group7: 'group 7',
  group8: 'group 8',
  groupA: 'group A',
  groupB: 'group B',
  groupC: 'group C',
  groupD: 'group D',
  groupE: 'group E',
  groupF: 'group F',
  groupg: 'group G',
  grouph: 'group H',
  finalGroup: 'group Final round',
  secondGroupRoundA: 'group A (second round)',
  secondGroupRoundB: 'group B (second round)',
  secondGroupRoundC: 'group C (second round)',
  secondGroupRoundD: 'group D (second round)',
}
