export type TournamentStages = {
  final: string
  finalGroupRound: string
  thirdPlace: string
  thirdPlaceGroupRound: string
  semiFinal: string
  quarterFinal: string
  roundOf16: string
  roundOf32: string
  group1: string
  group2: string
  group3: string
  group4: string
  group5: string
  group6: string
  group7: string
  group8: string
  groupA: string
  groupB: string
  groupC: string
  groupD: string
  groupE: string
  groupF: string
  groupg: string
  grouph: string
  finalGroup: string
  secondGroupRoundA: string
  secondGroupRoundB: string
  secondGroupRoundC: string
  secondGroupRoundD: string
}
